<?php

/**
 * Created by Curious Minds Media.
 * User: Andrew Engstrom (andrew@curiousm.com)
 * Date: 7/8/16
 * Time: 1:00 PM
 */

use Illuminate\Database\Seeder;

class FieldSeeder extends Seeder
{

    public function run()
    {

        $fields = [
            [
                'label'    => 'Company',
                'name'     => 'company',
                'type'     => 'text',
                'group'    => 'Customer OEM',
                'value'    => null,
                'options'  => null,
                'required' => true,
                'visible'  => true
            ],
            [
                'label'    => 'Address',
                'name'     => 'address',
                'type'     => 'text',
                'group'    => 'Customer OEM',
                'value'    => null,
                'options'  => null,
                'required' => false,
                'visible'  => true
            ],
            [
                'label'    => 'City',
                'name'     => 'city',
                'type'     => 'text',
                'group'    => 'Customer OEM',
                'value'    => null,
                'options'  => null,
                'required' => false,
                'visible'  => true
            ],
            [
                'label'    => 'State/County',
                'name'     => 'stateCounty',
                'type'     => 'dropdown',
                'group'    => 'Customer OEM',
                'value'    => null,
                'options'  => json_encode([
                    ['AK', 'US'],
                    ['AL', 'US'],
                    ['AR', 'US'],
                    ['AZ', 'US'],
                    ['CA', 'US'],
                    ['CO', 'US'],
                    ['CT', 'US'],
                    ['DE', 'US'],
                    ['FL', 'US'],
                    ['GA', 'US'],
                    ['HI', 'US'],
                    ['IA', 'US'],
                    ['ID', 'US'],
                    ['IL', 'US'],
                    ['IN', 'US'],
                    ['KS', 'US'],
                    ['KY', 'US'],
                    ['LA', 'US'],
                    ['MA', 'US'],
                    ['MD', 'US'],
                    ['ME', 'US'],
                    ['MI', 'US'],
                    ['MN', 'US'],
                    ['MO', 'US'],
                    ['MS', 'US'],
                    ['MT', 'US'],
                    ['NC', 'US'],
                    ['ND', 'US'],
                    ['NE', 'US'],
                    ['NH', 'US'],
                    ['NJ', 'US'],
                    ['NM', 'US'],
                    ['NV', 'US'],
                    ['NY', 'US'],
                    ['OH', 'US'],
                    ['OK', 'US'],
                    ['OR', 'US'],
                    ['PA', 'US'],
                    ['RI', 'US'],
                    ['SC', 'US'],
                    ['SD', 'US'],
                    ['TN', 'US'],
                    ['TX', 'US'],
                    ['UT', 'US'],
                    ['VA', 'US'],
                    ['VT', 'US'],
                    ['WA', 'US'],
                    ['WI', 'US'],
                    ['WV', 'US'],
                    ['WY', 'US'],
                    ['DC', 'US'],
                    ['PR', 'US'],
                    ['Scotland', 'GB'],
                    ['Northern England ', 'GB'],
                    ['North Wales ', 'GB'],
                    ['Shropshire', 'GB'],
                    ['Derbyshire', 'GB'],
                    ['Staffordshire', 'GB'],
                    ['Cheshire', 'GB'],
                    ['Greater Manchester', 'GB'],
                    ['Merseyside', 'GB'],
                    ['Lancashire', 'GB'],
                    ['Yorkshire', 'GB'],
                    ['Humberside', 'GB'],
                    ['Nottinghamshire', 'GB'],
                    ['Cambridgeshire', 'GB'],
                    ['Bedfordshire', 'GB'],
                    ['Northamptonshire', 'GB'],
                    ['Warwickshire', 'GB'],
                    ['Leicestershire', 'GB'],
                    ['Hereford & Worcester', 'GB'],
                    ['West Midlands', 'GB'],
                    ['Kent', 'GB'],
                    ['Hertfordshire', 'GB'],
                    ['Essex', 'GB'],
                    ['Norfolk & Suffolk', 'GB'],
                    ['Lincolnshire', 'GB'],
                    ['London', 'GB'],
                    ['East Sussex', 'GB'],
                    ['West Sussex', 'GB'],
                    ['Surrey', 'GB'],
                    ['Hampshire', 'GB'],
                    ['Berkshire', 'GB'],
                    ['Dorset', 'GB'],
                    ['Somerset', 'GB'],
                    ['Devon & Cornwall', 'GB'],
                    ['Wiltshire', 'GB'],
                    ['Avon', 'GB'],
                    ['South Wales', 'GB'],
                    ['Gloucestershire', 'GB'],
                    ['Oxfordshire', 'GB'],
                    ['Buckinghamshire', 'GB']
                ]),
                'required' => false,
                'visible'  => true
            ],
            [
                'label'    => 'Mail Code',
                'name'     => 'mailCode',
                'type'     => 'text',
                'group'    => 'Customer OEM',
                'value'    => null,
                'options'  => null,
                'required' => false,
                'visible'  => true
            ],
            [
                'label'    => 'Country',
                'name'     => 'country',
                'type'     => 'dropdown',
                'group'    => 'Customer OEM',
                'value'    => null,
                'options'  => json_encode([
                    ['Afghanistan', ''],
                    ['Albania', ''],
                    ['Algeria', ''],
                    ['Andorra', ''],
                    ['Angola', ''],
                    ['Anguilla', ''],
                    ['Antarctica', ''],
                    ['Antigua', ''],
                    ['Argentina', ''],
                    ['Armenia', ''],
                    ['Aruba', ''],
                    ['Australia', ''],
                    ['Austria', ''],
                    ['Azerbaijan', ''],
                    ['Bahamas', ''],
                    ['Bahrain', ''],
                    ['Bangladesh', ''],
                    ['Barbados', ''],
                    ['Belarus', ''],
                    ['Belgium', ''],
                    ['Belize', ''],
                    ['Benin', ''],
                    ['Bermuda', ''],
                    ['Bhutan', ''],
                    ['Bolivia', ''],
                    ['Bosnia/Hercegovina', ''],
                    ['Botswana', ''],
                    ['Brazil', ''],
                    ['Brunei', ''],
                    ['Bulgaria', ''],
                    ['Burkina Faso', ''],
                    ['Burma', ''],
                    ['Burundi', ''],
                    ['Cambodia Dem.', ''],
                    ['Cameroon', ''],
                    ['Canada', ''],
                    ['Cape Verde', ''],
                    ['Cayman Is.', ''],
                    ['Central African Republic', ''],
                    ['Chad', ''],
                    ['Chile', ''],
                    ['China', ''],
                    ['Cocos Is.', ''],
                    ['Colombia', ''],
                    ['Comoros', ''],
                    ['Congo', ''],
                    ['Cook Is.', ''],
                    ['Costa Rica', ''],
                    ['Cote D Ivoire', ''],
                    ['Croatia', ''],
                    ['Cuba', ''],
                    ['Cyprus', ''],
                    ['Czech Republic', ''],
                    ['Denmark', ''],
                    ['Djibouti', ''],
                    ['Dominica', ''],
                    ['Dominican Rep.', ''],
                    ['Ecuador', ''],
                    ['Egypt', ''],
                    ['El Salvador', ''],
                    ['Equatorial Guinea', ''],
                    ['Estonia', ''],
                    ['Ethiopia', ''],
                    ['Falkland Is.', ''],
                    ['Faroe Is.', ''],
                    ['Fiji', ''],
                    ['Finland', ''],
                    ['France', ''],
                    ['French Guiana', ''],
                    ['French Polynesia', ''],
                    ['Gabon', ''],
                    ['Gambia', ''],
                    ['Georgia', ''],
                    ['Germany', ''],
                    ['Ghana', ''],
                    ['Gibraltar', ''],
                    ['Greece', ''],
                    ['Greenland', ''],
                    ['Grenada', ''],
                    ['Guadeloupe', ''],
                    ['Guam', ''],
                    ['Guatemala', ''],
                    ['Guinea', ''],
                    ['Guinea-Bissau', ''],
                    ['Guyana', ''],
                    ['Haiti', ''],
                    ['Honduras', ''],
                    ['Hong Kong', ''],
                    ['Hungary', ''],
                    ['Iceland', ''],
                    ['India', ''],
                    ['Indonesia', ''],
                    ['Iran', ''],
                    ['Iraq', ''],
                    ['Ireland', ''],
                    ['Israel', ''],
                    ['Italy', ''],
                    ['Jamaica', ''],
                    ['Japan', ''],
                    ['Jordan', ''],
                    ['Kazakhstan', ''],
                    ['Kenya', ''],
                    ['Kiribati', ''],
                    ['Korea', ''],
                    ['Kuwait', ''],
                    ['Laos Peoples Dem. Rep.', ''],
                    ['Latvia', ''],
                    ['Lebanon', ''],
                    ['Lesotho', ''],
                    ['Liberia', ''],
                    ['Libyan Arab Jamahiriya', ''],
                    ['Liechtenstein', ''],
                    ['Lithuania', ''],
                    ['Luxembourg', ''],
                    ['Macau', ''],
                    ['Madagascar', ''],
                    ['Malawi', ''],
                    ['Malaysia', ''],
                    ['Maldives', ''],
                    ['Mali', ''],
                    ['Malta', ''],
                    ['Marshall Is.', ''],
                    ['Martinique', ''],
                    ['Mauritania', ''],
                    ['Mauritius', ''],
                    ['Mayotte', ''],
                    ['Mexico', ''],
                    ['Micronesia', ''],
                    ['Moldova', ''],
                    ['Monaco', ''],
                    ['Mongolia', ''],
                    ['Montserrat', ''],
                    ['Morocco', ''],
                    ['Mozambique', ''],
                    ['Myanmar', ''],
                    ['Namibia', ''],
                    ['Nauru', ''],
                    ['Nepal', ''],
                    ['Neth. Antilles Nevis', ''],
                    ['Netherlands', ''],
                    ['New Caledonia', ''],
                    ['New Zealand', ''],
                    ['Nicaragua', ''],
                    ['Niger', ''],
                    ['Nigeria', ''],
                    ['Niue', ''],
                    ['Norfolk Is.', ''],
                    ['Northern Mariana', ''],
                    ['Norway', ''],
                    ['Oman', ''],
                    ['Pakistan', ''],
                    ['Palau', ''],
                    ['Panama', ''],
                    ['Papua New Guinea', ''],
                    ['Paraguay', ''],
                    ['Peru', ''],
                    ['Philippines', ''],
                    ['Poland', ''],
                    ['Portugal', ''],
                    ['Puerto Rico', ''],
                    ['Qatar', ''],
                    ['Reunion', ''],
                    ['Romania', ''],
                    ['Russia', ''],
                    ['Rwanda', ''],
                    ['Samoa (American)', ''],
                    ['Samoa (Western)', ''],
                    ['San Marino', ''],
                    ['Sao Tome & Principe', ''],
                    ['Saudi Arabia', ''],
                    ['Senegal', ''],
                    ['Seychelles', ''],
                    ['Sierra Leone', ''],
                    ['Singapore', ''],
                    ['Slovakia', ''],
                    ['Slovenia', ''],
                    ['Solomon Is.', ''],
                    ['Somalia', ''],
                    ['South Africa', ''],
                    ['Spain', ''],
                    ['Sri Lanka', ''],
                    ['St. Kitts & Nevis', ''],
                    ['St. Lucia', ''],
                    ['St. Pierre & Miquelon', ''],
                    ['St. Vincent & Grenadines', ''],
                    ['Sudan', ''],
                    ['Suriname', ''],
                    ['Swaziland', ''],
                    ['Sweden', ''],
                    ['Switzerland', ''],
                    ['Syrian Arab Rep.', ''],
                    ['Taiwan', ''],
                    ['Tajikistan', ''],
                    ['Tanzania', ''],
                    ['Thailand', ''],
                    ['Togo', ''],
                    ['Tonga', ''],
                    ['Trinidad & Tobago', ''],
                    ['Tunisia', ''],
                    ['Turkey', ''],
                    ['Turkmenistan', ''],
                    ['Turks & Caicos', ''],
                    ['Tuvalu', ''],
                    ['Uganda', ''],
                    ['Ukraine', ''],
                    ['United Arab Emirates', ''],
                    ['United Kingdom', ''],
                    ['United States', ''],
                    ['Uruguay', ''],
                    ['Uzbeistan', ''],
                    ['Vanuatu', ''],
                    ['Vatican City', ''],
                    ['Venezuela', ''],
                    ['Vietnam', ''],
                    ['Virgin Is. (Br.)', ''],
                    ['Virgin Is. (U.S.)', ''],
                    ['Wallis & Futuna', ''],
                    ['Yemen Rep.', ''],
                    ['Yugoslavia', ''],
                    ['Zaire', ''],
                    ['Zambia', ''],
                    ['Zimbabwe']
                ]),
                'required' => true,
                'visible'  => true
            ],
            [
                'label'    => 'Contact Name',
                'name'     => 'contactName',
                'type'     => 'text',
                'group'    => 'Customer OEM',
                'value'    => null,
                'options'  => null,
                'required' => false,
                'visible'  => true
            ],
            [
                'label'    => 'Contact Title',
                'name'     => 'contactTitle',
                'type'     => 'text',
                'group'    => 'Customer OEM',
                'value'    => null,
                'options'  => null,
                'required' => false,
                'visible'  => true
            ],
            [
                'label'    => 'Contact Phone',
                'name'     => 'contactPhone',
                'type'     => 'text',
                'group'    => 'Customer OEM',
                'value'    => null,
                'options'  => null,
                'required' => false,
                'visible'  => true
            ],
            [
                'label'    => 'Contact Email',
                'name'     => 'contactEmail',
                'type'     => 'text',
                'group'    => 'Customer OEM',
                'value'    => null,
                'options'  => null,
                'required' => false,
                'visible'  => true
            ],
            [
                'label'    => 'Sales Rep Agent',
                'name'     => 'salesRepAgent',
                'type'     => 'dropdown',
                'group'    => 'Sales Channel',
                'value'    => null,
                'options'  => null,
                'required' => false,
                'visible'  => true
            ],
            [
                'label'    => 'Distributor',
                'name'     => 'distributor',
                'type'     => 'dropdown',
                'group'    => 'Sales Channel',
                'value'    => null,
                'options'  => json_encode([
                    ['ELECTRONIQUE DIFFUSION', 'FR'],
                    ['FARNELL IN ONE', 'FR'],
                    ['RS ELECTRONICS, LTD.', 'GB'],
                    ['FARNELL IN ONE', 'GB'],
                    ['ELFA', 'SE'],
                    ['YLEIS', 'SE'],
                    ['KGK', 'SE'],
                    ['BENNIKE AND WANDER', 'SE'],
                    ['HENACO', 'SE'],
                    ['FINNEKI', 'SE'],
                    ['Abacus Deltron Austria Gmbh', 'DK'],
                    ['NONE', 'US'],
                    ['OTHER', 'US'],
                    ['NONE', 'DK'],
                    ['OTHER', 'DK'],
                    ['NONE', 'SE'],
                    ['OTHER', 'SE'],
                    ['NONE', 'GB'],
                    ['OTHER', 'GB'],
                    ['NONE', 'FR'],
                    ['OTHER', 'FR'],
                    ['Abacus Deltron GmbH', 'DK'],
                    ['Abacus ECC Srl', 'DK'],
                    ['Active Components (NZ) Ltd.', 'DK'],
                    ['APEM AB', 'DK'],
                    ['APEM Benelux', 'DK'],
                    ['APEM Components Ltd.', 'DK'],
                    ['Asian Automation Associates Ltd', 'DK'],
                    ['Associated Controls Pty. Ltd.', 'DK'],
                    ['Brabek (Pty) Ltd', 'DK'],
                    ['Compex GmbH', 'DK'],
                    ['Constronica Lda', 'DK'],
                    ['Deltron France', 'DK'],
                    ['Egli, Fischer & Co. AG', 'DK'],
                    ['ELPROMA Elektronika Sp. z o.o.', 'DK'],
                    ['Enika spol.s r.o.', 'DK'],
                    ['Ermec, SL', 'DK'],
                    ['Flexitron Komponenter AB', 'DK'],
                    ['Freber Norge A/S', 'DK'],
                    ['General Elect. & Instr. Corp. Pte. Ltd.', 'DK'],
                    ['Group Tower Electronics Ltd.', 'DK'],
                    ['J.D. Friderichsen A/S', 'DK'],
                    ['KPI Co. Ltd.', 'DK'],
                    ['MFC Fulcrum', 'DK'],
                    ['Natthapong Sales & Service Co., Ltd.', 'DK'],
                    ['Nylund Group', 'DK'],
                    ['Produtos Eletronicos Metaltex Ltda.', 'DK'],
                    ['RS Components A/S', 'DK'],
                    ['Seltronics GmbH', 'DK'],
                    ['Sharon Industrial Agencies', 'DK'],
                    ['Smart Electronics Ltd', 'DK'],
                    ['Solico Inc.', 'DK'],
                    ['Trancy Inc.', 'DK'],
                    ['Vantronic S.A.', 'DK'],
                    ['AD-TECH ELECTRONICS INC', 'US'],
                    ['ARTLAND TECHNOLOGY LTD', 'US'],
                    ['BEYOND COMPONENTS (CT)', 'US'],
                    ['BROTHERS ELECTRONICS', 'US'],
                    ['CARLTON-BATES', 'US'],
                    ['DENVER BETA WINTRONIC', 'US'],
                    ['DEPENDABLE COMPONENT SUPPLY', 'US'],
                    ['DIVERSE ELECTRONICS', 'US'],
                    ['GO ELECTRONICS', 'US'],
                    ['HARDWARE SPECIALTY ATLANTA', 'US'],
                    ['HAWK ELECTRONICS', 'US'],
                    ['HEILIND ELECTRONICS', 'US'],
                    ['HUGHES-PETERS', 'US'],
                    ['IEC/WALKER COMPONENTS', 'US'],
                    ['JFL ELECTRONICS PTE LTD', 'US'],
                    ['KSM ELECTRONICS', 'US'],
                    ['MARSH ELECTRONICS INC', 'US'],
                    ['MASLINE ELECTRONICS INC.', 'US'],
                    ['MASTER DISTRIBUTORS', 'US'],
                    ['MCMASTER-CARR', 'US'],
                    ['MIDAN ELECTRONICS', 'US'],
                    ['MOUSER ELECTRONICS', 'US'],
                    ['NEDCO (AZ)', 'US'],
                    ['NEP ELECTRONICS', 'US'],
                    ['NEWARK INONE', 'US'],
                    ['NRC ELECTRONICS', 'US'],
                    ['PROGRESSIVE IMAGE', 'US'],
                    ['PROJECTIONS UNLIMITED (PUI)', 'US'],
                    ['RADAR ELECTRIC CO.', 'US'],
                    ['RELAY SPECIALTIES', 'US'],
                    ['RUSH ELECTRONICS', 'US'],
                    ['S KAHANE AGENCIES LTD', 'US'],
                    ['SIMCONA', 'US'],
                    ['SPEMCO', 'US'],
                    ['SWITCHING DEVICES', 'US'],
                    ['VOYAGER ELECTRONICS', 'US'],
                    ['WES-GARDE COMPONENTS', 'US'],
                    ['SELECTRONIC', 'FR'],
                    ['ATLANTIQUE Composants', 'FR'],
                    ['Groupe REXEL', 'FR'],
                    ['PN ELECTRONICS', 'FR'],
                    ['QUALISUD (Groupe Corel)', 'FR'],
                    ['AVNET TIME', 'FR'],
                    ['BRN Composants', 'FR'],
                    ['CEL', 'FR'],
                    ['ETN', 'FR'],
                    ['FGET International', 'FR'],
                    ['MATELCO', 'FR'],
                    ['RADIALEX Wurth', 'FR'],
                    ['RUTRONIK', 'FR'],
                    ['ERMEC', 'FR'],
                    ['REDISLOGAR', 'FR'],
                    ['PEERLESS ELECTRONICS', 'US'],
                    ['DigiKey', 'US'],
                    ['J-Squared', 'US']
                ]),
                'required' => false,
                'visible'  => true
            ],
            [
                'label'    => 'APEM Sales Person',
                'name'     => 'apemSalesPerson',
                'type'     => 'dropdown',
                'group'    => 'Sales Channel',
                'value'    => null,
                'options'  => json_encode([
                    ['Klaus Sinner', 'DE'],
                    ['Kurt Ortner', 'DE'],
                    ['Josef Stahl', 'DE'],
                    ['Sabine Brandl', 'DE'],
                    ['Florian Schmidl', 'DE'],
                    ['Urban Widerdal', 'SE'],
                    ['Ann-Marie Pettersson', 'SE'],
                    ['Thierry Van Geyseghem', 'BE'],
                    ['Jean Saint-Romas', 'FR'],
                    ['Laurent Fleury', 'FR'],
                    ['Gregory Guenoun', 'FR'],
                    ['Veronique Lagasse', 'FR'],
                    ['Jean-Martial Dejean', 'FR'],
                    ['Peter Hill', 'GB'],
                    ['Mike Pearman', 'GB'],
                    ['Jim Haston', 'GB'],
                    ['Simon Nunn', 'GB'],
                    ['Adam Kroll', 'GB'],
                    ['Lynn Bagshoot', 'GB'],
                    ['Jeremy Cooke', 'GB'],
                    ['Stuart McRae', 'GB'],
                    ['Yves Foccaert', 'BE'],
                    ['Giacomo Marengo', 'IT'],
                    ['Tony West', 'GB'],
                    ['Stefan Steiner', 'SE'],
                    ['Roy Harris', 'GB'],
                    ['Ian Mcstay', 'GB'],
                    ['Richard Bateman', 'GB'],
                    ['Steve Wallen', 'GB'],
                    ['Steve Blackwell', 'GB'],
                    ['Neil Smith', 'GB'],
                    ['Ivan Gam', 'DK'],
                    ['Claus Enoch', 'DK'],
                    ['Olivier Sterckx', 'FR'],
                    ['Jochen Beckers', 'BE'],
                    ['Ann Ferrin', 'BE'],
                    ['Curt Van Parijs', 'BE'],
                    ['Allen Homonoff', 'US'],
                    ['Peter Brouillette', 'US'],
                    ['Tony Solis', 'US'],
                    ['Bob Piotrowski', 'US'],
                    ['Nadine Geeraerts', 'BE'],
                    ['Joost Van Wijngaarde', 'BE'],
                    ['Arnaud Le Nahenec', 'FR'],
                    ['Pierre-Hugues Makowski ', 'FR'],
                    ['Florence Geniez', 'FR'],
                    ['Sylvie Birou', 'FR'],
                    ['Morten Hojdevang', 'DK'],
                    ['Eric Plantie', 'FR'],
                    ['Norbert Meyers', 'DE'],
                    ['Patrick Vandenplas', 'BE'],
                    ['Alessandro Galvagno', 'IT'],
                    ['Winnie Xu', 'CN'],
                    ['Tian Yi', 'CN'],
                    ['Fei Qi Bo', 'CN'],
                    ['Guoping Xu', 'CN'],
                    ['Bryan Murphy', 'US'],
                    ['Marc Mondeteguy', 'FR'],
                    ['Hugues Roquefort', 'FR'],
                    ['Angelique Mothes', 'FR'],
                    ['Sophie Prevost', 'FR'],
                    ['Michael Schulze', 'DE'],
                    ['Sascha Laub', 'DE'],
                    ['Manfred Holten', 'DE'],
                    ['Martin Döllinger', 'DE'],
                    ['Christoph Obermüller', 'DE'],
                    ['Céline Deloye', 'FR'],
                    ['Bernd Geebelen', 'BE'],
                    ['Brian Tovtin', 'US'],
                    ['Magnus Edvall', 'SE'],
                    ['Mark Petersen', 'US'],
                    ['Neil Murphy', 'US'],
                    ['Bambi Tierney', 'US']
                ]),
                'required' => true,
                'visible'  => true
            ],
            [
                'label'    => 'SRA Sales Rep',
                'name'     => 'sraSalesRep',
                'type'     => 'text',
                'group'    => 'Sales Channel',
                'value'    => null,
                'options'  => null,
                'required' => false,
                'visible'  => true
            ],
            [
                'label'    => 'Distributor Salesperson',
                'name'     => 'distributorSalesperson',
                'type'     => 'text',
                'group'    => 'Sales Channel',
                'value'    => null,
                'options'  => null,
                'required' => false,
                'visible'  => true
            ],
            [
                'label'    => 'Industry',
                'name'     => 'industry',
                'type'     => 'dropdown',
                'group'    => 'Sales Channel',
                'value'    => null,
                'options'  => json_encode([
                    ['', ''],
                    ['Telecom', ''],
                    ['Computers & Peripherals', ''],
                    ['Medical', ''],
                    ['Instrumentation', ''],
                    ['Security', ''],
                    ['Industrial', ''],
                    ['Consumer', ''],
                    ['Transportation (non-auto)', ''],
                    ['Automotive', ''],
                    ['Off-road', ''],
                    ['Appliance', ''],
                    ['Marine', ''],
                    ['Mil/Aero', '']
                ]),
                'required' => true,
                'visible'  => true
            ],
            [
                'label'    => 'Application',
                'name'     => 'application',
                'type'     => 'text',
                'group'    => 'Sales Channel',
                'value'    => null,
                'options'  => null,
                'required' => true,
                'visible'  => true
            ],
            [
                'label'    => 'Reason for Opp',
                'name'     => 'reasonForOpp',
                'type'     => 'dropdown',
                'group'    => 'Sales Channel',
                'value'    => null,
                'options'  => json_encode([
                    ['Delivery Issues', ''],
                    ['New Program', ''],
                    ['Price Reduction', ''],
                    ['Quality Issues', ''],
                    ['Vendor Reduction', ''],
                    ['Other', '']
                ]),
                'required' => true,
                'visible'  => true
            ],
            [
                'label'    => 'Function',
                'name'     => 'function',
                'type'     => 'text',
                'group'    => 'Sales Channel',
                'value'    => null,
                'options'  => null,
                'required' => false,
                'visible'  => true
            ],
            [
                'label'    => 'Catalog Product',
                'name'     => 'catalogProduct',
                'type'     => 'radio',
                'group'    => 'Product Description',
                'value'    => null,
                'options'  => null,
                'required' => false,
                'visible'  => true
            ],
            [
                'label'    => 'Catalog Part Number',
                'name'     => 'catalogPartNum',
                'type'     => 'text',
                'group'    => 'Product Description',
                'value'    => null,
                'options'  => null,
                'required' => false,
                'visible'  => true
            ],
            [
                'label'    => 'Customer Part Number',
                'name'     => 'customerPartNum',
                'type'     => 'text',
                'group'    => 'Product Description',
                'value'    => null,
                'options'  => null,
                'required' => false,
                'visible'  => true
            ],
            [
                'label'    => 'Product Type',
                'name'     => 'productType',
                'type'     => 'dropdown',
                'group'    => 'Product Description',
                'value'    => null,
                'options'  => json_encode([
                    ['Keylock', ''],
                    ['Indicators', ''],
                    ['MEC', ''],
                    ['Industrial Control', ''],
                    ['Joystick', ''],
                    ['Membrane/Keyboards', ''],
                    ['Other', ''],
                    ['Push Button', ''],
                    ['Push Wheel', ''],
                    ['Rocker', ''],
                    ['Rotary', ''],
                    ['Rubber Keypad', ''],
                    ['Slide', ''],
                    ['Snap Switch', ''],
                    ['SS Keypad', ''],
                    ['Toggle', ''],
                    ['DIP', ''],
                    ['Knobs', ''],
                    ['Tact', ''],
                    ['Trackball', ''],
                    ['Thumbwheel', '']
                ]),
                'required' => true,
                'visible'  => true
            ],

            [
                'label'    => 'Product Series',
                'name'     => 'productSeries',
                'type'     => 'dropdown',
                'group'    => 'Product Description',
                'value'    => null,
                'options'  => json_encode([
                    ['Navimec', ''],
                    ['660', ''],
                    ['1000', ''],
                    ['1500', ''],
                    ['3500', ''],
                    ['5000', ''],
                    ['6000', ''],
                    ['10600', ''],
                    ['11000', ''],
                    ['12000', ''],
                    ['55000', ''],
                    ['12000X778', ''],
                    ['1600/1700', ''],
                    ['21000N', ''],
                    ['3600NF', ''],
                    ['4600/4400', ''],
                    ['600H', ''],
                    ['600NH', ''],
                    ['S and SF', ''],
                    ['SMT TL', ''],
                    ['ST', ''],
                    ['TL', ''],
                    ['ZL', ''],
                    ['300', ''],
                    ['400', ''],
                    ['800', ''],
                    ['1200', ''],
                    ['4700', ''],
                    ['4800', ''],
                    ['8000', ''],
                    ['9100', ''],
                    ['9200', ''],
                    ['9400', ''],
                    ['9500', ''],
                    ['9600', ''],
                    ['10400', ''],
                    ['13000', ''],
                    ['18000', ''],
                    ['1200M', ''],
                    ['1200MR', ''],
                    ['13000X778', ''],
                    ['1400N', ''],
                    ['A01', ''],
                    ['A01ES', ''],
                    ['A02', ''],
                    ['A02ES', ''],
                    ['A03', ''],
                    ['A1', ''],
                    ['AV', ''],
                    ['IA', ''],
                    ['IB-IS', ''],
                    ['IF', ''],
                    ['IP', ''],
                    ['IT', ''],
                    ['PBA', ''],
                    ['PHAP40', ''],
                    ['SMT TP', ''],
                    ['SP', ''],
                    ['TP', ''],
                    ['ZP', ''],
                    ['ADTS', ''],
                    ['ADTS3', ''],
                    ['ADTSHJM', ''],
                    ['AMPT', ''],
                    ['APT', ''],
                    ['ATM', ''],
                    ['MHPS', ''],
                    ['MJTP/12mm', ''],
                    ['MJTP/4mm', ''],
                    ['MJTP/6mm', ''],
                    ['MTP', ''],
                    ['2600', ''],
                    ['7000', ''],
                    ['AS', ''],
                    ['B', ''],
                    ['FM', ''],
                    ['HB', ''],
                    ['KG', ''],
                    ['KR', ''],
                    ['MR', ''],
                    ['R', ''],
                    ['RH', ''],
                    ['S', ''],
                    ['SMT TR', ''],
                    ['SR', ''],
                    ['ST', ''],
                    ['TR', ''],
                    ['25000N', ''],
                    ['G', ''],
                    ['M', ''],
                    ['MA', ''],
                    ['MHS', ''],
                    ['MHSS', ''],
                    ['MJS', ''],
                    ['MMS', ''],
                    ['MS', ''],
                    ['MSL', ''],
                    ['MSS', ''],
                    ['MSSA', ''],
                    ['MSTS', ''],
                    ['NK', ''],
                    ['PM', ''],
                    ['SLA', ''],
                    ['SLB', ''],
                    ['SLC', ''],
                    ['SLG', ''],
                    ['SMT TG', ''],
                    ['TG', ''],
                    ['CR36', ''],
                    ['CR36S', ''],
                    ['CR65', ''],
                    ['DA', ''],
                    ['DHS', ''],
                    ['DM', ''],
                    ['DP', ''],
                    ['DPL', ''],
                    ['DS', ''],
                    ['DSR', ''],
                    ['IKN', ''],
                    ['MPG', ''],
                    ['NDI', ''],
                    ['NHDS', ''],
                    ['P36', ''],
                    ['P36S', ''],
                    ['P60A', ''],
                    ['P60AS', ''],
                    ['PT65', ''],
                    ['A1', ''],
                    ['A01', ''],
                    ['A02', ''],
                    ['A03', ''],
                    ['VL', ''],
                    ['B', ''],
                    ['P36', ''],
                    ['P36S', ''],
                    ['CR36', ''],
                    ['PT65', ''],
                    ['CR65', ''],
                    ['P60A', ''],
                    ['P60AS', ''],
                    ['JD', ''],
                    ['A01', ''],
                    ['A02', ''],
                    ['1000', ''],
                    ['4000', ''],
                    ['5000', ''],
                    ['9000', ''],
                    ['SH6/6G/6S', ''],
                    ['PICOD', ''],
                    ['SMCD', ''],
                    ['DPS8', ''],
                    ['DPS9', ''],
                    ['DPS10', ''],
                    ['Socket', ''],
                    ['MB', ''],
                    ['MA', ''],
                    ['MDB1', ''],
                    ['Aluminum', ''],
                    ['Molded ABS', ''],
                    ['Molded Phenolic', ''],
                    ['MEC', ''],
                    ['Membrane/Keyboards', ''],
                    ['Rubber Keypads', ''],
                    ['SS Keypads', ''],
                    ['Other', ''],
                    ['Q', ''],
                    ['Multimec 3A', ''],
                    ['Multimec 3C', ''],
                    ['Multimec 3E', ''],
                    ['Multimec 3F', ''],
                    ['Illumec', ''],
                    ['Varimec', ''],
                    ['Aquamec', ''],
                    ['Unimec', ''],
                    ['Non-Catalog', ''],
                    ['Non-Catalog', ''],
                    ['Non-Catalog', ''],
                    ['Other CH', ''],
                    ['Non-Catalog', ''],
                    ['Non-Catalog', ''],
                    ['Non-Catalog', ''],
                    ['Non-Catalog', ''],
                    ['Non-Catalog', ''],
                    ['Non-Catalog', ''],
                    ['Non-Catalog', ''],
                    ['Non-Catalog', ''],
                    ['Non-Catalog', ''],
                    ['Non-Catalog', ''],
                    ['Non-Catalog', ''],
                    ['CH Resistive Series', ''],
                    ['HFX Series I', ''],
                    ['HFX Series II', ''],
                    ['HFX Series III', ''],
                    ['HFX Series IV', ''],
                    ['HFX Single Axis Throttle', ''],
                    ['T-Bar Fader', ''],
                    ['R Series', ''],
                    ['LP Series', ''],
                    ['P Series', ''],
                    ['DT Series', ''],
                    ['CH Rocker', ''],
                    ['HFX Thumbwheel', ''],
                    ['3000', ''],
                    ['8000', ''],
                    ['IP - USB desktops', ''],
                    ['Other UK', ''],
                    ['IRR', ''],
                    ['IZ', ''],
                    ['IPP', ''],
                    ['MT', ''],
                    ['CT', ''],
                    ['Multimec 5G', ''],
                    ['Multimec 5E', ''],
                    ['Foilmec']
                ]),
                'required' => true,
                'visible'  => true
            ],
            [
                'label'    => 'APEM Part Number',
                'name'     => 'apemPartNumber',
                'type'     => 'text',
                'group'    => 'Product Description',
                'value'    => null,
                'options'  => null,
                'required' => false,
                'visible'  => true
            ],
            [
                'label'    => 'Brief Description',
                'name'     => 'briefDescription',
                'type'     => 'text',
                'group'    => 'Product Description',
                'value'    => null,
                'options'  => null,
                'required' => false,
                'visible'  => true
            ],
            [
                'label'    => 'Extended Description',
                'name'     => 'extendedDescription',
                'type'     => 'text',
                'group'    => 'Product Description',
                'value'    => null,
                'options'  => null,
                'required' => false,
                'visible'  => true
            ],
            [
                'label'    => 'Current Supplier',
                'name'     => 'currentSupplier',
                'type'     => 'dropdown',
                'group'    => 'Competitors',
                'value'    => null,
                'options'  => json_encode([
                    ['ELECTRONIQUE DIFFUSION', 'FR'],
                    ['FARNELL IN ONE', 'FR'],
                    ['RS ELECTRONICS, LTD.', 'GB'],
                    ['FARNELL IN ONE', 'GB'],
                    ['ELFA', 'SE'],
                    ['YLEIS', 'SE'],
                    ['KGK', 'SE'],
                    ['BENNIKE AND WANDER', 'SE'],
                    ['HENACO', 'SE'],
                    ['FINNEKI', 'SE'],
                    ['Abacus Deltron Austria Gmbh', 'DK'],
                    ['NONE', 'US'],
                    ['OTHER', 'US'],
                    ['NONE', 'DK'],
                    ['OTHER', 'DK'],
                    ['NONE', 'SE'],
                    ['OTHER', 'SE'],
                    ['NONE', 'GB'],
                    ['OTHER', 'GB'],
                    ['NONE', 'FR'],
                    ['OTHER', 'FR'],
                    ['Abacus Deltron GmbH', 'DK'],
                    ['Abacus ECC Srl', 'DK'],
                    ['Active Components (NZ) Ltd.', 'DK'],
                    ['APEM AB', 'DK'],
                    ['APEM Benelux', 'DK'],
                    ['APEM Components Ltd.', 'DK'],
                    ['Asian Automation Associates Ltd', 'DK'],
                    ['Associated Controls Pty. Ltd.', 'DK'],
                    ['Brabek (Pty) Ltd', 'DK'],
                    ['Compex GmbH', 'DK'],
                    ['Constronica Lda', 'DK'],
                    ['Deltron France', 'DK'],
                    ['Egli, Fischer & Co. AG', 'DK'],
                    ['ELPROMA Elektronika Sp. z o.o.', 'DK'],
                    ['Enika spol.s r.o.', 'DK'],
                    ['Ermec, SL', 'DK'],
                    ['Flexitron Komponenter AB', 'DK'],
                    ['Freber Norge A/S', 'DK'],
                    ['General Elect. & Instr. Corp. Pte. Ltd.', 'DK'],
                    ['Group Tower Electronics Ltd.', 'DK'],
                    ['J.D. Friderichsen A/S', 'DK'],
                    ['KPI Co. Ltd.', 'DK'],
                    ['MFC Fulcrum', 'DK'],
                    ['Natthapong Sales & Service Co., Ltd.', 'DK'],
                    ['Nylund Group', 'DK'],
                    ['Produtos Eletronicos Metaltex Ltda.', 'DK'],
                    ['RS Components A/S', 'DK'],
                    ['Seltronics GmbH', 'DK'],
                    ['Sharon Industrial Agencies', 'DK'],
                    ['Smart Electronics Ltd', 'DK'],
                    ['Solico Inc.', 'DK'],
                    ['Trancy Inc.', 'DK'],
                    ['Vantronic S.A.', 'DK'],
                    ['AD-TECH ELECTRONICS INC', 'US'],
                    ['ARTLAND TECHNOLOGY LTD', 'US'],
                    ['BEYOND COMPONENTS (CT)', 'US'],
                    ['BROTHERS ELECTRONICS', 'US'],
                    ['CARLTON-BATES', 'US'],
                    ['DENVER BETA WINTRONIC', 'US'],
                    ['DEPENDABLE COMPONENT SUPPLY', 'US'],
                    ['DIVERSE ELECTRONICS', 'US'],
                    ['GO ELECTRONICS', 'US'],
                    ['HARDWARE SPECIALTY ATLANTA', 'US'],
                    ['HAWK ELECTRONICS', 'US'],
                    ['HEILIND ELECTRONICS', 'US'],
                    ['HUGHES-PETERS', 'US'],
                    ['IEC/WALKER COMPONENTS', 'US'],
                    ['JFL ELECTRONICS PTE LTD', 'US'],
                    ['KSM ELECTRONICS', 'US'],
                    ['MARSH ELECTRONICS INC', 'US'],
                    ['MASLINE ELECTRONICS INC.', 'US'],
                    ['MASTER DISTRIBUTORS', 'US'],
                    ['MCMASTER-CARR', 'US'],
                    ['MIDAN ELECTRONICS', 'US'],
                    ['MOUSER ELECTRONICS', 'US'],
                    ['NEDCO (AZ)', 'US'],
                    ['NEP ELECTRONICS', 'US'],
                    ['NEWARK INONE', 'US'],
                    ['NRC ELECTRONICS', 'US'],
                    ['PROGRESSIVE IMAGE', 'US'],
                    ['PROJECTIONS UNLIMITED (PUI)', 'US'],
                    ['RADAR ELECTRIC CO.', 'US'],
                    ['RELAY SPECIALTIES', 'US'],
                    ['RUSH ELECTRONICS', 'US'],
                    ['S KAHANE AGENCIES LTD', 'US'],
                    ['SIMCONA', 'US'],
                    ['SPEMCO', 'US'],
                    ['SWITCHING DEVICES', 'US'],
                    ['VOYAGER ELECTRONICS', 'US'],
                    ['WES-GARDE COMPONENTS', 'US'],
                    ['SELECTRONIC', 'FR'],
                    ['ATLANTIQUE Composants', 'FR'],
                    ['Groupe REXEL', 'FR'],
                    ['PN ELECTRONICS', 'FR'],
                    ['QUALISUD (Groupe Corel)', 'FR'],
                    ['AVNET TIME', 'FR'],
                    ['BRN Composants', 'FR'],
                    ['CEL', 'FR'],
                    ['ETN', 'FR'],
                    ['FGET International', 'FR'],
                    ['MATELCO', 'FR'],
                    ['RADIALEX Wurth', 'FR'],
                    ['RUTRONIK', 'FR'],
                    ['ERMEC', 'FR'],
                    ['REDISLOGAR', 'FR'],
                    ['PEERLESS ELECTRONICS', 'US'],
                    ['DigiKey', 'US'],
                    ['J-Squared', 'US']
                ]),
                'required' => true,
                'visible'  => true
            ],
            [
                'label'    => 'Competitors',
                'name'     => 'competitors',
                'type'     => 'dropdown',
                'group'    => 'Competitors',
                'value'    => null,
                'options'  => json_encode([
                    ['Joseph Pollack', ''],
                    ['Happ Controls', ''],
                    ['Honeywell', ''],
                    ['Otto', ''],
                    ['Colehersee', ''],
                    ['Schurter', ''],
                    ['CH Products', ''],
                    ['CTI Electronics', ''],
                    ['Molex', ''],
                    ['Penny & Giles', ''],
                    ['Sakae', ''],
                    ['Telemechanique', ''],
                    ['Advanced Input System', ''],
                    ['Bergquist', ''],
                    ['Miller Dial', ''],
                    ['None', ''],
                    ['Xymox', ''],
                    ['Nelson Nameplate', ''],
                    ['Alps', ''],
                    ['AMP', ''],
                    ['Arcolectric', ''],
                    ['Ark-Les', ''],
                    ['Augat/Alcoswitch', ''],
                    ['Carlingswitch', ''],
                    ['Cherry', ''],
                    ['CTS', ''],
                    ['Diptronics', ''],
                    ['E-Switch', ''],
                    ['EAO', ''],
                    ['Eaton', ''],
                    ['Grayhill', ''],
                    ['C&K', ''],
                    ['ITW Switches', ''],
                    ['Knitter Switch', ''],
                    ['Korry Electronics', ''],
                    ['Marquardt', ''],
                    ['Microswitch', ''],
                    ['NKK', ''],
                    ['None', ''],
                    ['Omron', ''],
                    ['Otax', ''],
                    ['Other (Specify)', ''],
                    ['SAIA-Burgess', ''],
                    ['SMK', ''],
                    ['Taiway', ''],
                    ['Berquist', ''],
                    ['Dow Switch', ''],
                    ['Eastprint', ''],
                    ['ECI Screenprint', ''],
                    ['GGI', ''],
                    ['Other (Specify)', ''],
                    ['Sun Coast', ''],
                    ['Techprint', ''],
                    ['Unknown', '']
                ]),
                'required' => true,
                'visible'  => true
            ],
            [
                'label'    => 'Year 1 Sales Volume',
                'name'     => 'year1SalesVol',
                'type'     => 'text',
                'group'    => 'Estimated Value',
                'value'    => null,
                'options'  => null,
                'required' => true,
                'visible'  => true
            ],
            [
                'label'    => 'Year 2 Sales Volume',
                'name'     => 'year2SalesVol',
                'type'     => 'text',
                'group'    => 'Estimated Value',
                'value'    => null,
                'options'  => null,
                'required' => true,
                'visible'  => true
            ],
            [
                'label'    => 'Year 3 Sales Volume',
                'name'     => 'year3SalesVol',
                'type'     => 'text',
                'group'    => 'Estimated Value',
                'value'    => null,
                'options'  => null,
                'required' => false,
                'visible'  => true
            ],
            [
                'label'    => 'Currency',
                'name'     => 'currency',
                'type'     => 'text',
                'group'    => 'Estimated Value',
                'value'    => null,
                'options'  => null,
                'required' => false,
                'visible'  => true
            ],
            [
                'label'    => 'Target Sales Price',
                'name'     => 'targetSalesPrice',
                'type'     => 'text',
                'group'    => 'Estimated Value',
                'value'    => null,
                'options'  => null,
                'required' => true,
                'visible'  => true
            ],
            [
                'label'    => 'Potential Annual Revenue',
                'name'     => 'potentialAnnualRev',
                'type'     => 'auto',
                'group'    => 'Estimated Value',
                'value'    => null,
                'options'  => null,
                'required' => false,
                'visible'  => true
            ],
            [
                'label'    => 'Probability of Win',
                'name'     => 'probabilityOfWin',
                'type'     => 'dropdown',
                'group'    => 'Estimated Value',
                'value'    => null,
                'options'  => json_encode([
                    ['0%', ''],
                    ['25%', ''],
                    ['50%', ''],
                    ['75%', ''],
                    ['100%', '']
                ]),
                'required' => true,
                'visible'  => true
            ],
            [
                'label'    => 'Expected Value',
                'name'     => 'expectedValue',
                'type'     => 'auto',
                'group'    => 'Estimated Value',
                'value'    => null,
                'options'  => null,
                'required' => false,
                'visible'  => true
            ],
            [
                'label'    => 'Quote Date',
                'name'     => 'quoteDate',
                'type'     => 'date',
                'group'    => 'Milestones',
                'value'    => null,
                'options'  => null,
                'required' => false,
                'visible'  => true
            ],
            [
                'label'    => 'Sample Date',
                'name'     => 'sampleDate',
                'type'     => 'date',
                'group'    => 'Milestones',
                'value'    => null,
                'options'  => null,
                'required' => false,
                'visible'  => true
            ],
            [
                'label'    => 'Approval Date',
                'name'     => 'approvalDate',
                'type'     => 'date',
                'group'    => 'Milestones',
                'value'    => null,
                'options'  => null,
                'required' => false,
                'visible'  => true
            ],
            [
                'label'    => 'Date Rcvd Prod Order',
                'name'     => 'dateRcvdProdOrder',
                'type'     => 'date',
                'group'    => 'Milestones',
                'value'    => null,
                'options'  => null,
                'required' => false,
                'visible'  => true
            ],
            [
                'label'    => 'Estimated Prod Date',
                'name'     => 'estimatedProdDate',
                'type'     => 'date',
                'group'    => 'Milestones',
                'value'    => null,
                'options'  => null,
                'required' => false,
                'visible'  => true
            ],
            [
                'label'    => 'Prod Sales Order Number',
                'name'     => 'prodSalesOrderNum',
                'type'     => 'text',
                'group'    => 'Milestones',
                'value'    => null,
                'options'  => null,
                'required' => false,
                'visible'  => true
            ],
            [
                'label'    => 'Reason for Win',
                'name'     => 'reasonForWin',
                'type'     => 'dropdown',
                'group'    => 'Milestones',
                'value'    => null,
                'options'  => json_encode([
                    ['Price', ''],
                    ['Lead Time', ''],
                    ['Response Time to RFQ', ''],
                    ['Product Quality', ''],
                    ['Product Innovation', ''],
                    ['Product Specification', '']
                ]),
                'required' => false,
                'visible'  => true
            ],

            [
                'label'    => 'DateLost',
                'name'     => 'dateLost',
                'type'     => 'date',
                'group'    => 'Milestones',
                'value'    => null,
                'options'  => null,
                'required' => false,
                'visible'  => true
            ],
            [
                'label'    => 'Lost to Whom',
                'name'     => 'lostToWhom',
                'type'     => 'dropdown',
                'group'    => 'Milestones',
                'value'    => null,
                'options'  => null,
                'required' => false,
                'visible'  => true
            ],
            [
                'label'    => 'Reason for Loss',
                'name'     => 'reasonForLoss',
                'type'     => 'dropdown',
                'group'    => 'Milestones',
                'value'    => null,
                'options'  => json_encode([
                    ['Excessive Lead Time', ''],
                    ['Price', ''],
                    ['Program Cancelled', ''],
                    ['Response Time to Quote', ''],
                    ['Technical Deficiencies', ''],
                    ['No Bid', ''],
                    ['Other', ''],
                    ['Not Known', '']
                ]),
                'required' => false,
                'visible'  => true
            ],

            [
                'label'    => 'Comment Field',
                'name'     => 'commentField',
                'type'     => 'textarea',
                'group'    => 'Comments',
                'value'    => null,
                'options'  => null,
                'required' => false,
                'visible'  => true
            ]
        ];

        DB::table('fields')->delete();

        foreach ($fields as $field) {
            $newField           = new \app\Models\Field();
            $newField->label    = $field['label'];
            $newField->name     = $field['name'];
            $newField->type     = $field['type'];
            $newField->group    = $field['group'];
            $newField->value    = $field['value'];
            $newField->options  = $field['options'];
            $newField->required = $field['required'];
            $newField->visible  = $field['visible'];
            $newField->save();
        }
    }

}
