<?php

/**
 * Created by Curious Minds Media.
 * User: Andrew Engstrom (andrew@curiousm.com)
 * Date: 7/8/16
 * Time: 1:00 PM
 */

use Illuminate\Database\Seeder;

class FieldSeeder extends Seeder
{

    public function run()
    {

        $fields = [
            [
                'label'    => 'Company',
                'name'     => 'company',
                'type'     => 'text',
                'group'    => 'Customer OEM',
                'value'    => null,
                'options'  => null,
                'required' => true,
                'visible'  => true
            ],
            [
                'label'    => 'Address',
                'name'     => 'address',
                'type'     => 'text',
                'group'    => 'Customer OEM',
                'value'    => null,
                'options'  => null,
                'required' => false,
                'visible'  => true
            ],
            [
                'label'    => 'City',
                'name'     => 'city',
                'type'     => 'text',
                'group'    => 'Customer OEM',
                'value'    => null,
                'options'  => null,
                'required' => false,
                'visible'  => true
            ],
            [
                'label'    => 'State/County',
                'name'     => 'stateCounty',
                'type'     => 'dropdown',
                'group'    => 'Customer OEM',
                'value'    => null,
                'options'  => json_encode([
                    ['AK', 'US'],
                    ['AL', 'US'],
                    ['AR', 'US'],
                    ['AZ', 'US'],
                    ['CA', 'US'],
                    ['CO', 'US'],
                    ['CT', 'US'],
                    ['DE', 'US'],
                    ['FL', 'US'],
                    ['GA', 'US'],
                    ['HI', 'US'],
                    ['IA', 'US'],
                    ['ID', 'US'],
                    ['IL', 'US'],
                    ['IN', 'US'],
                    ['KS', 'US'],
                    ['KY', 'US'],
                    ['LA', 'US'],
                    ['MA', 'US'],
                    ['MD', 'US'],
                    ['ME', 'US'],
                    ['MI', 'US'],
                    ['MN', 'US'],
                    ['MO', 'US'],
                    ['MS', 'US'],
                    ['MT', 'US'],
                    ['NC', 'US'],
                    ['ND', 'US'],
                    ['NE', 'US'],
                    ['NH', 'US'],
                    ['NJ', 'US'],
                    ['NM', 'US'],
                    ['NV', 'US'],
                    ['NY', 'US'],
                    ['OH', 'US'],
                    ['OK', 'US'],
                    ['OR', 'US'],
                    ['PA', 'US'],
                    ['RI', 'US'],
                    ['SC', 'US'],
                    ['SD', 'US'],
                    ['TN', 'US'],
                    ['TX', 'US'],
                    ['UT', 'US'],
                    ['VA', 'US'],
                    ['VT', 'US'],
                    ['WA', 'US'],
                    ['WI', 'US'],
                    ['WV', 'US'],
                    ['WY', 'US'],
                    ['DC', 'US'],
                    ['PR', 'US'],
                    ['Scotland', 'GB'],
                    ['Northern England ', 'GB'],
                    ['North Wales ', 'GB'],
                    ['Shropshire', 'GB'],
                    ['Derbyshire', 'GB'],
                    ['Staffordshire', 'GB'],
                    ['Cheshire', 'GB'],
                    ['Greater Manchester', 'GB'],
                    ['Merseyside', 'GB'],
                    ['Lancashire', 'GB'],
                    ['Yorkshire', 'GB'],
                    ['Humberside', 'GB'],
                    ['Nottinghamshire', 'GB'],
                    ['Cambridgeshire', 'GB'],
                    ['Bedfordshire', 'GB'],
                    ['Northamptonshire', 'GB'],
                    ['Warwickshire', 'GB'],
                    ['Leicestershire', 'GB'],
                    ['Hereford & Worcester', 'GB'],
                    ['West Midlands', 'GB'],
                    ['Kent', 'GB'],
                    ['Hertfordshire', 'GB'],
                    ['Essex', 'GB'],
                    ['Norfolk & Suffolk', 'GB'],
                    ['Lincolnshire', 'GB'],
                    ['London', 'GB'],
                    ['East Sussex', 'GB'],
                    ['West Sussex', 'GB'],
                    ['Surrey', 'GB'],
                    ['Hampshire', 'GB'],
                    ['Berkshire', 'GB'],
                    ['Dorset', 'GB'],
                    ['Somerset', 'GB'],
                    ['Devon & Cornwall', 'GB'],
                    ['Wiltshire', 'GB'],
                    ['Avon', 'GB'],
                    ['South Wales', 'GB'],
                    ['Gloucestershire', 'GB'],
                    ['Oxfordshire', 'GB'],
                    ['Buckinghamshire', 'GB']
                ]),
                'required' => false,
                'visible'  => true
            ],
            [
                'label'    => 'Mail Code',
                'name'     => 'mailCode',
                'type'     => 'text',
                'group'    => 'Customer OEM',
                'value'    => null,
                'options'  => null,
                'required' => false,
                'visible'  => true
            ],
            [
                'label'    => 'Country',
                'name'     => 'country',
                'type'     => 'dropdown',
                'group'    => 'Customer OEM',
                'value'    => null,
                'options'  => json_encode([
                    ['Afghanistan', ''],
                    ['Albania', ''],
                    ['Algeria', ''],
                    ['Andorra', ''],
                    ['Angola', ''],
                    ['Anguilla', ''],
                    ['Antarctica', ''],
                    ['Antigua', ''],
                    ['Argentina', ''],
                    ['Armenia', ''],
                    ['Aruba', ''],
                    ['Australia', ''],
                    ['Austria', ''],
                    ['Azerbaijan', ''],
                    ['Bahamas', ''],
                    ['Bahrain', ''],
                    ['Bangladesh', ''],
                    ['Barbados', ''],
                    ['Belarus', ''],
                    ['Belgium', ''],
                    ['Belize', ''],
                    ['Benin', ''],
                    ['Bermuda', ''],
                    ['Bhutan', ''],
                    ['Bolivia', ''],
                    ['Bosnia/Hercegovina', ''],
                    ['Botswana', ''],
                    ['Brazil', ''],
                    ['Brunei', ''],
                    ['Bulgaria', ''],
                    ['Burkina Faso', ''],
                    ['Burma', ''],
                    ['Burundi', ''],
                    ['Cambodia Dem.', ''],
                    ['Cameroon', ''],
                    ['Canada', ''],
                    ['Cape Verde', ''],
                    ['Cayman Is.', ''],
                    ['Central African Republic', ''],
                    ['Chad', ''],
                    ['Chile', ''],
                    ['China', ''],
                    ['Cocos Is.', ''],
                    ['Colombia', ''],
                    ['Comoros', ''],
                    ['Congo', ''],
                    ['Cook Is.', ''],
                    ['Costa Rica', ''],
                    ['Cote D Ivoire', ''],
                    ['Croatia', ''],
                    ['Cuba', ''],
                    ['Cyprus', ''],
                    ['Czech Republic', ''],
                    ['Denmark', ''],
                    ['Djibouti', ''],
                    ['Dominica', ''],
                    ['Dominican Rep.', ''],
                    ['Ecuador', ''],
                    ['Egypt', ''],
                    ['El Salvador', ''],
                    ['Equatorial Guinea', ''],
                    ['Estonia', ''],
                    ['Ethiopia', ''],
                    ['Falkland Is.', ''],
                    ['Faroe Is.', ''],
                    ['Fiji', ''],
                    ['Finland', ''],
                    ['France', ''],
                    ['French Guiana', ''],
                    ['French Polynesia', ''],
                    ['Gabon', ''],
                    ['Gambia', ''],
                    ['Georgia', ''],
                    ['Germany', ''],
                    ['Ghana', ''],
                    ['Gibraltar', ''],
                    ['Greece', ''],
                    ['Greenland', ''],
                    ['Grenada', ''],
                    ['Guadeloupe', ''],
                    ['Guam', ''],
                    ['Guatemala', ''],
                    ['Guinea', ''],
                    ['Guinea-Bissau', ''],
                    ['Guyana', ''],
                    ['Haiti', ''],
                    ['Honduras', ''],
                    ['Hong Kong', ''],
                    ['Hungary', ''],
                    ['Iceland', ''],
                    ['India', ''],
                    ['Indonesia', ''],
                    ['Iran', ''],
                    ['Iraq', ''],
                    ['Ireland', ''],
                    ['Israel', ''],
                    ['Italy', ''],
                    ['Jamaica', ''],
                    ['Japan', ''],
                    ['Jordan', ''],
                    ['Kazakhstan', ''],
                    ['Kenya', ''],
                    ['Kiribati', ''],
                    ['Korea', ''],
                    ['Kuwait', ''],
                    ['Laos Peoples Dem. Rep.', ''],
                    ['Latvia', ''],
                    ['Lebanon', ''],
                    ['Lesotho', ''],
                    ['Liberia', ''],
                    ['Libyan Arab Jamahiriya', ''],
                    ['Liechtenstein', ''],
                    ['Lithuania', ''],
                    ['Luxembourg', ''],
                    ['Macau', ''],
                    ['Madagascar', ''],
                    ['Malawi', ''],
                    ['Malaysia', ''],
                    ['Maldives', ''],
                    ['Mali', ''],
                    ['Malta', ''],
                    ['Marshall Is.', ''],
                    ['Martinique', ''],
                    ['Mauritania', ''],
                    ['Mauritius', ''],
                    ['Mayotte', ''],
                    ['Mexico', ''],
                    ['Micronesia', ''],
                    ['Moldova', ''],
                    ['Monaco', ''],
                    ['Mongolia', ''],
                    ['Montserrat', ''],
                    ['Morocco', ''],
                    ['Mozambique', ''],
                    ['Myanmar', ''],
                    ['Namibia', ''],
                    ['Nauru', ''],
                    ['Nepal', ''],
                    ['Neth. Antilles Nevis', ''],
                    ['Netherlands', ''],
                    ['New Caledonia', ''],
                    ['New Zealand', ''],
                    ['Nicaragua', ''],
                    ['Niger', ''],
                    ['Nigeria', ''],
                    ['Niue', ''],
                    ['Norfolk Is.', ''],
                    ['Northern Mariana', ''],
                    ['Norway', ''],
                    ['Oman', ''],
                    ['Pakistan', ''],
                    ['Palau', ''],
                    ['Panama', ''],
                    ['Papua New Guinea', ''],
                    ['Paraguay', ''],
                    ['Peru', ''],
                    ['Philippines', ''],
                    ['Poland', ''],
                    ['Portugal', ''],
                    ['Puerto Rico', ''],
                    ['Qatar', ''],
                    ['Reunion', ''],
                    ['Romania', ''],
                    ['Russia', ''],
                    ['Rwanda', ''],
                    ['Samoa (American)', ''],
                    ['Samoa (Western)', ''],
                    ['San Marino', ''],
                    ['Sao Tome & Principe', ''],
                    ['Saudi Arabia', ''],
                    ['Senegal', ''],
                    ['Seychelles', ''],
                    ['Sierra Leone', ''],
                    ['Singapore', ''],
                    ['Slovakia', ''],
                    ['Slovenia', ''],
                    ['Solomon Is.', ''],
                    ['Somalia', ''],
                    ['South Africa', ''],
                    ['Spain', ''],
                    ['Sri Lanka', ''],
                    ['St. Kitts & Nevis', ''],
                    ['St. Lucia', ''],
                    ['St. Pierre & Miquelon', ''],
                    ['St. Vincent & Grenadines', ''],
                    ['Sudan', ''],
                    ['Suriname', ''],
                    ['Swaziland', ''],
                    ['Sweden', ''],
                    ['Switzerland', ''],
                    ['Syrian Arab Rep.', ''],
                    ['Taiwan', ''],
                    ['Tajikistan', ''],
                    ['Tanzania', ''],
                    ['Thailand', ''],
                    ['Togo', ''],
                    ['Tonga', ''],
                    ['Trinidad & Tobago', ''],
                    ['Tunisia', ''],
                    ['Turkey', ''],
                    ['Turkmenistan', ''],
                    ['Turks & Caicos', ''],
                    ['Tuvalu', ''],
                    ['Uganda', ''],
                    ['Ukraine', ''],
                    ['United Arab Emirates', ''],
                    ['United Kingdom', ''],
                    ['United States', ''],
                    ['Uruguay', ''],
                    ['Uzbeistan', ''],
                    ['Vanuatu', ''],
                    ['Vatican City', ''],
                    ['Venezuela', ''],
                    ['Vietnam', ''],
                    ['Virgin Is. (Br.)', ''],
                    ['Virgin Is. (U.S.)', ''],
                    ['Wallis & Futuna', ''],
                    ['Yemen Rep.', ''],
                    ['Yugoslavia', ''],
                    ['Zaire', ''],
                    ['Zambia', ''],
                    ['Zimbabwe']
                ]),
                'required' => true,
                'visible'  => true
            ],
            [
                'label'    => 'Contact Name',
                'name'     => 'contactName',
                'type'     => 'text',
                'group'    => 'Customer OEM',
                'value'    => null,
                'options'  => null,
                'required' => false,
                'visible'  => true
            ],
            [
                'label'    => 'Contact Title',
                'name'     => 'contactTitle',
                'type'     => 'text',
                'group'    => 'Customer OEM',
                'value'    => null,
                'options'  => null,
                'required' => false,
                'visible'  => true
            ],
            [
                'label'    => 'Contact Phone',
                'name'     => 'contactPhone',
                'type'     => 'text',
                'group'    => 'Customer OEM',
                'value'    => null,
                'options'  => null,
                'required' => false,
                'visible'  => true
            ],
            [
                'label'    => 'Contact Email',
                'name'     => 'contactEmail',
                'type'     => 'text',
                'group'    => 'Customer OEM',
                'value'    => null,
                'options'  => null,
                'required' => false,
                'visible'  => true
            ],
            [
                'label'    => 'Sales Rep Agent',
                'name'     => 'salesRepAgent',
                'type'     => 'dropdown',
                'group'    => 'Sales Channel',
                'value'    => null,
                'options'  => json_encode([
                    ['FR- Firm 1', 'FR'],
                    ['FR- Firm 2', 'FR'],
                    ['FR- Firm 3', 'FR'],
                    ['FR- Firm 4', 'FR'],
                    ['FR- Firm 5', 'FR'],
                    ['US- All-Tech', 'US'],
                    ['US- APEM Direct', 'US'],
                    ['US- Synergy Sales', 'US'],
                    ['US- ECS (Electronic Component Sales)', 'US'],
                    ['US- W28', 'US'],
                    ['US- Intercompany', 'US'],
                    ['US- Xtronics', 'US'],
                    ['US- Dytec-NCI', 'US'],
                    ['US- Graham Performance Tech', 'US'],
                    ['US- Rendell Sales', 'US'],
                    ['US- Synergistic Component Sales', 'US'],
                    ['US- ODonnell', 'US'],
                    ['US- Mindshare', 'US'],
                    ['US- Recht Associates', 'US'],
                    ['US- CentraMark', 'US'],
                    ['US- Wallace', 'US'],
                    ['US- English Damco Sales Co. ', 'US'],
                    ['US- Centech Inc.', 'US']
                ]),
                'required' => false,
                'visible'  => true
            ],
            [
                'label'    => 'Distributor',
                'name'     => 'distributor',
                'type'     => 'dropdown',
                'group'    => 'Sales Channel',
                'value'    => null,
                'options'  => json_encode([
                    ['ELECTRONIQUE DIFFUSION', 'FR'],
                    ['FARNELL IN ONE', 'FR'],
                    ['RS ELECTRONICS, LTD.', 'GB'],
                    ['FARNELL IN ONE', 'GB'],
                    ['ELFA', 'SE'],
                    ['YLEIS', 'SE'],
                    ['KGK', 'SE'],
                    ['BENNIKE AND WANDER', 'SE'],
                    ['HENACO', 'SE'],
                    ['FINNEKI', 'SE'],
                    ['Abacus Deltron Austria Gmbh', 'DK'],
                    ['NONE', 'US'],
                    ['OTHER', 'US'],
                    ['NONE', 'DK'],
                    ['OTHER', 'DK'],
                    ['NONE', 'SE'],
                    ['OTHER', 'SE'],
                    ['NONE', 'GB'],
                    ['OTHER', 'GB'],
                    ['NONE', 'FR'],
                    ['OTHER', 'FR'],
                    ['Abacus Deltron GmbH', 'DK'],
                    ['Abacus ECC Srl', 'DK'],
                    ['Active Components (NZ) Ltd.', 'DK'],
                    ['APEM AB', 'DK'],
                    ['APEM Benelux', 'DK'],
                    ['APEM Components Ltd.', 'DK'],
                    ['Asian Automation Associates Ltd', 'DK'],
                    ['Associated Controls Pty. Ltd.', 'DK'],
                    ['Brabek (Pty) Ltd', 'DK'],
                    ['Compex GmbH', 'DK'],
                    ['Constronica Lda', 'DK'],
                    ['Deltron France', 'DK'],
                    ['Egli, Fischer & Co. AG', 'DK'],
                    ['ELPROMA Elektronika Sp. z o.o.', 'DK'],
                    ['Enika spol.s r.o.', 'DK'],
                    ['Ermec, SL', 'DK'],
                    ['Flexitron Komponenter AB', 'DK'],
                    ['Freber Norge A/S', 'DK'],
                    ['General Elect. & Instr. Corp. Pte. Ltd.', 'DK'],
                    ['Group Tower Electronics Ltd.', 'DK'],
                    ['J.D. Friderichsen A/S', 'DK'],
                    ['KPI Co. Ltd.', 'DK'],
                    ['MFC Fulcrum', 'DK'],
                    ['Natthapong Sales & Service Co., Ltd.', 'DK'],
                    ['Nylund Group', 'DK'],
                    ['Produtos Eletronicos Metaltex Ltda.', 'DK'],
                    ['RS Components A/S', 'DK'],
                    ['Seltronics GmbH', 'DK'],
                    ['Sharon Industrial Agencies', 'DK'],
                    ['Smart Electronics Ltd', 'DK'],
                    ['Solico Inc.', 'DK'],
                    ['Trancy Inc.', 'DK'],
                    ['Vantronic S.A.', 'DK'],
                    ['AD-TECH ELECTRONICS INC', 'US'],
                    ['ARTLAND TECHNOLOGY LTD', 'US'],
                    ['BEYOND COMPONENTS (CT)', 'US'],
                    ['BROTHERS ELECTRONICS', 'US'],
                    ['CARLTON-BATES', 'US'],
                    ['DENVER BETA WINTRONIC', 'US'],
                    ['DEPENDABLE COMPONENT SUPPLY', 'US'],
                    ['DIVERSE ELECTRONICS', 'US'],
                    ['GO ELECTRONICS', 'US'],
                    ['HARDWARE SPECIALTY ATLANTA', 'US'],
                    ['HAWK ELECTRONICS', 'US'],
                    ['HEILIND ELECTRONICS', 'US'],
                    ['HUGHES-PETERS', 'US'],
                    ['IEC/WALKER COMPONENTS', 'US'],
                    ['JFL ELECTRONICS PTE LTD', 'US'],
                    ['KSM ELECTRONICS', 'US'],
                    ['MARSH ELECTRONICS INC', 'US'],
                    ['MASLINE ELECTRONICS INC.', 'US'],
                    ['MASTER DISTRIBUTORS', 'US'],
                    ['MCMASTER-CARR', 'US'],
                    ['MIDAN ELECTRONICS', 'US'],
                    ['MOUSER ELECTRONICS', 'US'],
                    ['NEDCO (AZ)', 'US'],
                    ['NEP ELECTRONICS', 'US'],
                    ['NEWARK INONE', 'US'],
                    ['NRC ELECTRONICS', 'US'],
                    ['PROGRESSIVE IMAGE', 'US'],
                    ['PROJECTIONS UNLIMITED (PUI)', 'US'],
                    ['RADAR ELECTRIC CO.', 'US'],
                    ['RELAY SPECIALTIES', 'US'],
                    ['RUSH ELECTRONICS', 'US'],
                    ['S KAHANE AGENCIES LTD', 'US'],
                    ['SIMCONA', 'US'],
                    ['SPEMCO', 'US'],
                    ['SWITCHING DEVICES', 'US'],
                    ['VOYAGER ELECTRONICS', 'US'],
                    ['WES-GARDE COMPONENTS', 'US'],
                    ['SELECTRONIC', 'FR'],
                    ['ATLANTIQUE Composants', 'FR'],
                    ['Groupe REXEL', 'FR'],
                    ['PN ELECTRONICS', 'FR'],
                    ['QUALISUD (Groupe Corel)', 'FR'],
                    ['AVNET TIME', 'FR'],
                    ['BRN Composants', 'FR'],
                    ['CEL', 'FR'],
                    ['ETN', 'FR'],
                    ['FGET International', 'FR'],
                    ['MATELCO', 'FR'],
                    ['RADIALEX Wurth', 'FR'],
                    ['RUTRONIK', 'FR'],
                    ['ERMEC', 'FR'],
                    ['REDISLOGAR', 'FR'],
                    ['PEERLESS ELECTRONICS', 'US'],
                    ['DigiKey', 'US'],
                    ['J-Squared', 'US']
                ]),
                'required' => false,
                'visible'  => true
            ],
            [
                'label'    => 'APEM Sales Person',
                'name'     => 'apemSalesPerson',
                'type'     => 'dropdown',
                'group'    => 'Sales Channel',
                'value'    => null,
                'options'  => json_encode([
                    ['Klaus Sinner', 'DE'],
                    ['Kurt Ortner', 'DE'],
                    ['Josef Stahl', 'DE'],
                    ['Sabine Brandl', 'DE'],
                    ['Florian Schmidl', 'DE'],
                    ['Urban Widerdal', 'SE'],
                    ['Ann-Marie Pettersson', 'SE'],
                    ['Thierry Van Geyseghem', 'BE'],
                    ['Jean Saint-Romas', 'FR'],
                    ['Laurent Fleury', 'FR'],
                    ['Gregory Guenoun', 'FR'],
                    ['Veronique Lagasse', 'FR'],
                    ['Jean-Martial Dejean', 'FR'],
                    ['Peter Hill', 'GB'],
                    ['Mike Pearman', 'GB'],
                    ['Jim Haston', 'GB'],
                    ['Simon Nunn', 'GB'],
                    ['Adam Kroll', 'GB'],
                    ['Lynn Bagshoot', 'GB'],
                    ['Jeremy Cooke', 'GB'],
                    ['Stuart McRae', 'GB'],
                    ['Yves Foccaert', 'BE'],
                    ['Giacomo Marengo', 'IT'],
                    ['Tony West', 'GB'],
                    ['Stefan Steiner', 'SE'],
                    ['Roy Harris', 'GB'],
                    ['Ian Mcstay', 'GB'],
                    ['Richard Bateman', 'GB'],
                    ['Steve Wallen', 'GB'],
                    ['Steve Blackwell', 'GB'],
                    ['Neil Smith', 'GB'],
                    ['Ivan Gam', 'DK'],
                    ['Claus Enoch', 'DK'],
                    ['Olivier Sterckx', 'FR'],
                    ['Jochen Beckers', 'BE'],
                    ['Ann Ferrin', 'BE'],
                    ['Curt Van Parijs', 'BE'],
                    ['Allen Homonoff', 'US'],
                    ['Peter Brouillette', 'US'],
                    ['Tony Solis', 'US'],
                    ['Bob Piotrowski', 'US'],
                    ['Nadine Geeraerts', 'BE'],
                    ['Joost Van Wijngaarde', 'BE'],
                    ['Arnaud Le Nahenec', 'FR'],
                    ['Pierre-Hugues Makowski ', 'FR'],
                    ['Florence Geniez', 'FR'],
                    ['Sylvie Birou', 'FR'],
                    ['Morten Hojdevang', 'DK'],
                    ['Eric Plantie', 'FR'],
                    ['Norbert Meyers', 'DE'],
                    ['Patrick Vandenplas', 'BE'],
                    ['Alessandro Galvagno', 'IT'],
                    ['Winnie Xu', 'CN'],
                    ['Tian Yi', 'CN'],
                    ['Fei Qi Bo', 'CN'],
                    ['Guoping Xu', 'CN'],
                    ['Bryan Murphy', 'US'],
                    ['Marc Mondeteguy', 'FR'],
                    ['Hugues Roquefort', 'FR'],
                    ['Angelique Mothes', 'FR'],
                    ['Sophie Prevost', 'FR'],
                    ['Michael Schulze', 'DE'],
                    ['Sascha Laub', 'DE'],
                    ['Manfred Holten', 'DE'],
                    ['Martin Döllinger', 'DE'],
                    ['Christoph Obermüller', 'DE'],
                    ['Céline Deloye', 'FR'],
                    ['Bernd Geebelen', 'BE'],
                    ['Brian Tovtin', 'US'],
                    ['Magnus Edvall', 'SE'],
                    ['Mark Petersen', 'US'],
                    ['Neil Murphy', 'US'],
                    ['Bambi Tierney', 'US']
                ]),
                'required' => true,
                'visible'  => true
            ],
            [
                'label'    => 'SRA Sales Rep',
                'name'     => 'sraSalesRep',
                'type'     => 'text',
                'group'    => 'Sales Channel',
                'value'    => null,
                'options'  => null,
                'required' => false,
                'visible'  => true
            ],
            [
                'label'    => 'Distributor Salesperson',
                'name'     => 'distributorSalesperson',
                'type'     => 'text',
                'group'    => 'Sales Channel',
                'value'    => null,
                'options'  => null,
                'required' => false,
                'visible'  => true
            ],
            [
                'label'    => 'Industry',
                'name'     => 'industry',
                'type'     => 'dropdown',
                'group'    => 'Sales Channel',
                'value'    => null,
                'options'  => json_encode([
                    ['', ''],
                    ['Agriculture', ''],
                    ['Automotive', ''],
                    ['Communication', ''],
                    ['Consumer Appliances, Computers and Peripherals', ''],
                    ['Industrial automation', ''],
                    ['Instrumentation (non-medical)', ''],
                    ['Marine', ''],
                    ['Material Handling', ''],
                    ['Medical', ''],
                    ['Military - Aerospace', ''],
                    ['Security', ''],
                    ['Vehicle - other', ''],
                    ['', '']
                ]),
                'required' => true,
                'visible'  => true
            ],
            [
                'label'    => 'Application',
                'name'     => 'application',
                'type'     => 'text',
                'group'    => 'Sales Channel',
                'value'    => null,
                'options'  => null,
                'required' => true,
                'visible'  => true
            ],
            [
                'label'    => 'Reason for Opp',
                'name'     => 'reasonForOpp',
                'type'     => 'dropdown',
                'group'    => 'Sales Channel',
                'value'    => null,
                'options'  => json_encode([
                    ['Delivery Issues', ''],
                    ['New Program', ''],
                    ['Price Reduction', ''],
                    ['Quality Issues', ''],
                    ['Vendor Reduction', ''],
                    ['Other', '']
                ]),
                'required' => true,
                'visible'  => true
            ],
            [
                'label'    => 'Function',
                'name'     => 'function',
                'type'     => 'text',
                'group'    => 'Sales Channel',
                'value'    => null,
                'options'  => null,
                'required' => false,
                'visible'  => true
            ],
            [
                'label'    => 'Catalog Product',
                'name'     => 'catalogProduct',
                'type'     => 'radio',
                'group'    => 'Product Description',
                'value'    => null,
                'options'  => null,
                'required' => false,
                'visible'  => true
            ],
            [
                'label'    => 'Catalog Part Number',
                'name'     => 'catalogPartNum',
                'type'     => 'text',
                'group'    => 'Product Description',
                'value'    => null,
                'options'  => null,
                'required' => false,
                'visible'  => true
            ],
            [
                'label'    => 'Customer Part Number',
                'name'     => 'customerPartNum',
                'type'     => 'text',
                'group'    => 'Product Description',
                'value'    => null,
                'options'  => null,
                'required' => false,
                'visible'  => true
            ],
            [
                'label'    => 'Product Type',
                'name'     => 'productType',
                'type'     => 'dropdown',
                'group'    => 'Product Description',
                'value'    => null,
                'options'  => json_encode([
                    ['Keylock', ''],
                    ['Indicators', ''],
                    ['MEC', ''],
                    ['Industrial Control', ''],
                    ['Joystick', ''],
                    ['Membrane/Keyboards', ''],
                    ['Other', ''],
                    ['Push Button', ''],
                    ['Push Wheel', ''],
                    ['Rocker', ''],
                    ['Rotary', ''],
                    ['Rubber Keypad', ''],
                    ['Slide', ''],
                    ['Snap Switch', ''],
                    ['SS Keypad', ''],
                    ['Toggle', ''],
                    ['DIP', ''],
                    ['Knobs', ''],
                    ['Tact', ''],
                    ['Trackball', ''],
                    ['Thumbwheel', '']
                ]),
                'required' => true,
                'visible'  => true
            ],

            [
                'label'    => 'Product Series',
                'name'     => 'productSeries',
                'type'     => 'dropdown',
                'group'    => 'Product Description',
                'value'    => null,
                'options'  => json_encode([
                  ['Navimec', 'MEC'],
                  ['660', 'Toggle'],
                  ['1000', 'Toggle'],
                  ['1500', 'Toggle'],
                  ['3500', 'Toggle'],
                  ['5000', 'Toggle'],
                  ['6000', 'Toggle'],
                  ['10600', 'Toggle'],
                  ['11000', 'Toggle'],
                  ['12000', 'Toggle'],
                  ['55000', 'Toggle'],
                  ['12000X778', 'Toggle'],
                  ['1600/1700', 'Toggle'],
                  ['21000N', 'Toggle'],
                  ['3600NF', 'Toggle'],
                  ['4600/4400', 'Toggle'],
                  ['600H', 'Toggle'],
                  ['600NH', 'Toggle'],
                  ['S and SF', 'Toggle'],
                  ['SMT TL', 'Toggle'],
                  ['ST', 'Toggle'],
                  ['TL', 'Toggle'],
                  ['ZL', 'Toggle'],
                  ['300', 'Push Button'],
                  ['400', 'Push Button'],
                  ['800', 'Push Button'],
                  ['1200', 'Push Button'],
                  ['4700', 'Push Button'],
                  ['4800', 'Push Button'],
                  ['8000', 'Push Button'],
                  ['9100', 'Push Button'],
                  ['9200', 'Push Button'],
                  ['9400', 'Push Button'],
                  ['9500', 'Push Button'],
                  ['9600', 'Push Button'],
                  ['10400', 'Push Button'],
                  ['13000', 'Push Button'],
                  ['18000', 'Push Button'],
                  ['1200M', 'Push Button'],
                  ['1200MR', 'Push Button'],
                  ['13000X778', 'Push Button'],
                  ['1400N', 'Push Button'],
                  ['A01', 'Push Button'],
                  ['A01ES', 'Push Button'],
                  ['A02', 'Push Button'],
                  ['A02ES', 'Push Button'],
                  ['A03', 'Push Button'],
                  ['A1', 'Push Button'],
                  ['AV', 'Push Button'],
                  ['IA', 'Push Button'],
                  ['IB-IS', 'Push Button'],
                  ['IF', 'Push Button'],
                  ['IP', 'Push Button'],
                  ['IT', 'Push Button'],
                  ['PBA', 'Push Button'],
                  ['PHAP40', 'Push Button'],
                  ['SMT TP', 'Push Button'],
                  ['SP', 'Push Button'],
                  ['TP', 'Push Button'],
                  ['ZP', 'Push Button'],
                  ['ADTS', 'Tact'],
                  ['ADTS3', 'Tact'],
                  ['ADTSHJM', 'Tact'],
                  ['AMPT', 'Tact'],
                  ['APT', 'Tact'],
                  ['ATM', 'Tact'],
                  ['MHPS', 'Tact'],
                  ['MJTP/12mm', 'Tact'],
                  ['MJTP/4mm', 'Tact'],
                  ['MJTP/6mm', 'Tact'],
                  ['MTP', 'Tact'],
                  ['2600', 'Rocker'],
                  ['7000', 'Rocker'],
                  ['AS', 'Rocker'],
                  ['B', 'Rocker'],
                  ['FM', 'Rocker'],
                  ['HB', 'Rocker'],
                  ['KG', 'Rocker'],
                  ['KR', 'Rocker'],
                  ['MR', 'Rocker'],
                  ['R', 'Rocker'],
                  ['RH', 'Rocker'],
                  ['S', 'Rocker'],
                  ['SMT TR', 'Rocker'],
                  ['SR', 'Rocker'],
                  ['ST', 'Rocker'],
                  ['TR', 'Rocker'],
                  ['25000N', 'Slide'],
                  ['G', 'Slide'],
                  ['M', 'Slide'],
                  ['MA', 'Slide'],
                  ['MHS', 'Slide'],
                  ['MHSS', 'Slide'],
                  ['MJS', 'Slide'],
                  ['MMS', 'Slide'],
                  ['MS', 'Slide'],
                  ['MSL', 'Slide'],
                  ['MSS', 'Slide'],
                  ['MSSA', 'Slide'],
                  ['MSTS', 'Slide'],
                  ['NK', 'Slide'],
                  ['PM', 'Slide'],
                  ['SLA', 'Slide'],
                  ['SLB', 'Slide'],
                  ['SLC', 'Slide'],
                  ['SLG', 'Slide'],
                  ['SMT TG', 'Slide'],
                  ['TG', 'Slide'],
                  ['CR36', 'DIP'],
                  ['CR36S', 'DIP'],
                  ['CR65', 'DIP'],
                  ['DA', 'DIP'],
                  ['DHS', 'DIP'],
                  ['DM', 'DIP'],
                  ['DP', 'DIP'],
                  ['DPL', 'DIP'],
                  ['DS', 'DIP'],
                  ['DSR', 'DIP'],
                  ['IKN', 'DIP'],
                  ['MPG', 'DIP'],
                  ['NDI', 'DIP'],
                  ['NHDS', 'DIP'],
                  ['P36', 'DIP'],
                  ['P36S', 'DIP'],
                  ['P60A', 'DIP'],
                  ['P60AS', 'DIP'],
                  ['PT65', 'DIP'],
                  ['A1', 'Industrial Control'],
                  ['A01', 'Industrial Control'],
                  ['A02', 'Industrial Control'],
                  ['A03', 'Industrial Control'],
                  ['VL', 'Indicators'],
                  ['B', 'Indicators'],
                  ['P36', 'Rotary'],
                  ['P36S', 'Rotary'],
                  ['CR36', 'Rotary'],
                  ['PT65', 'Rotary'],
                  ['CR65', 'Rotary'],
                  ['P60A', 'Rotary'],
                  ['P60AS', 'Rotary'],
                  ['JD', 'Keylock'],
                  ['A01', 'Keylock'],
                  ['A02', 'Keylock'],
                  ['1000', 'Joystick'],
                  ['4000', 'Joystick'],
                  ['5000', 'Joystick'],
                  ['9000', 'Joystick'],
                  ['SH6/6G/6S', 'Push Wheel'],
                  ['PICOD', 'Push Wheel'],
                  ['SMCD', 'Push Wheel'],
                  ['DPS8', 'Push Wheel'],
                  ['DPS9', 'Push Wheel'],
                  ['DPS10', 'Push Wheel'],
                  ['Socket', 'Push Wheel'],
                  ['MB', 'Snap Switch'],
                  ['MA', 'Snap Switch'],
                  ['MDB1', 'Snap Switch'],
                  ['Aluminum', 'Knobs'],
                  ['Molded ABS', 'Knobs'],
                  ['Molded Phenolic', 'Knobs'],
                  ['MEC', 'MEC'],
                  ['Membrane/Keyboards', 'Membrane/Keyboards'],
                  ['Rubber Keypads', 'Rubber Keypad'],
                  ['SS Keypads', 'SS Keypad'],
                  ['Other', 'Other'],
                  ['Q', 'Indicators'],
                  ['Multimec 3A', 'MEC'],
                  ['Multimec 3C', 'MEC'],
                  ['Multimec 3E', 'MEC'],
                  ['Multimec 3F', 'MEC'],
                  ['Illumec', 'MEC'],
                  ['Varimec', 'MEC'],
                  ['Aquamec', 'MEC'],
                  ['Unimec', 'MEC'],
                  ['Non-Catalog', 'Keylock'],
                  ['Non-Catalog', 'Indicators'],
                  ['Non-Catalog', 'Industrial Control'],
                  ['Other CH', 'Joystick'],
                  ['Non-Catalog', 'Push Button'],
                  ['Non-Catalog', 'Push Wheel'],
                  ['Non-Catalog', 'Rocker'],
                  ['Non-Catalog', 'Rotary'],
                  ['Non-Catalog', 'Slide'],
                  ['Non-Catalog', 'Snap Switch'],
                  ['Non-Catalog', 'DIP'],
                  ['Non-Catalog', 'Toggle'],
                  ['Non-Catalog', 'SS Keypad'],
                  ['Non-Catalog', 'Knobs'],
                  ['Non-Catalog', 'Tact'],
                  ['CH Resistive Series', 'Joystick'],
                  ['HFX Series I', 'Joystick'],
                  ['HFX Series II', 'Joystick'],
                  ['HFX Series III', 'Joystick'],
                  ['HFX Series IV', 'Joystick'],
                  ['HFX Single Axis Throttle', 'Joystick'],
                  ['T-Bar Fader', 'Joystick'],
                  ['R Series', 'Trackball'],
                  ['LP Series', 'Trackball'],
                  ['P Series', 'Trackball'],
                  ['DT Series', 'Trackball'],
                  ['CH Rocker', 'Rocker'],
                  ['HFX Thumbwheel', 'Thumbwheel'],
                  ['3000', 'Joystick'],
                  ['8000', 'Joystick'],
                  ['IP - USB desktops', 'Joystick'],
                  ['Other UK', 'Joystick'],
                  ['IRR', 'Push Button'],
                  ['IZ', 'Push Button'],
                  ['IPP', 'Push Button'],
                  ['MT', 'Toggle'],
                  ['CT', 'Toggle'],
                  ['Multimec 5G', 'MEC'],
                  ['Multimec 5E', 'MEC'],
                  ['Foilmec', 'MEC']
                ]),
                'required' => true,
                'visible'  => true
            ],
            [
                'label'    => 'APEM Part Number',
                'name'     => 'apemPartNumber',
                'type'     => 'text',
                'group'    => 'Product Description',
                'value'    => null,
                'options'  => null,
                'required' => false,
                'visible'  => true
            ],
            [
                'label'    => 'Brief Description',
                'name'     => 'briefDescription',
                'type'     => 'text',
                'group'    => 'Product Description',
                'value'    => null,
                'options'  => null,
                'required' => false,
                'visible'  => true
            ],
            [
                'label'    => 'Extended Description',
                'name'     => 'extendedDescription',
                'type'     => 'text',
                'group'    => 'Product Description',
                'value'    => null,
                'options'  => null,
                'required' => false,
                'visible'  => true
            ],
            [
                'label'    => 'Current Supplier',
                'name'     => 'currentSupplier',
                'type'     => 'dropdown',
                'group'    => 'Competitors',
                'value'    => null,
                'options'  => json_encode([
                    ['Joseph Pollack', ''],
                    ['Happ Controls', ''],
                    ['Honeywell', ''],
                    ['Otto', ''],
                    ['Colehersee', ''],
                    ['Schurter', ''],
                    ['CH Products', ''],
                    ['CTI Electronics', ''],
                    ['Molex', ''],
                    ['Penny & Giles', ''],
                    ['Sakae', ''],
                    ['Telemechanique', ''],
                    ['Advanced Input System', ''],
                    ['Bergquist', ''],
                    ['Miller Dial', ''],
                    ['None', ''],
                    ['Xymox', ''],
                    ['Nelson Nameplate', ''],
                    ['Alps', ''],
                    ['AMP', ''],
                    ['Arcolectric', ''],
                    ['Ark-Les', ''],
                    ['Augat/Alcoswitch', ''],
                    ['Carlingswitch', ''],
                    ['Cherry', ''],
                    ['CTS', ''],
                    ['Diptronics', ''],
                    ['E-Switch', ''],
                    ['EAO', ''],
                    ['Eaton', ''],
                    ['Grayhill', ''],
                    ['C&K', ''],
                    ['ITW Switches', ''],
                    ['Knitter Switch', ''],
                    ['Korry Electronics', ''],
                    ['Marquardt', ''],
                    ['Microswitch', ''],
                    ['NKK', ''],
                    ['None', ''],
                    ['Omron', ''],
                    ['Otax', ''],
                    ['Other (Specify)', ''],
                    ['SAIA-Burgess', ''],
                    ['SMK', ''],
                    ['Taiway', ''],
                    ['Berquist', ''],
                    ['Dow Switch', ''],
                    ['Eastprint', ''],
                    ['ECI Screenprint', ''],
                    ['GGI', ''],
                    ['Other (Specify)', ''],
                    ['Sun Coast', ''],
                    ['Techprint', ''],
                    ['Unknown', '']
                ]),
                'required' => true,
                'visible'  => true
            ],
            [
                'label'    => 'Competitors',
                'name'     => 'competitors',
                'type'     => 'dropdown',
                'group'    => 'Competitors',
                'value'    => null,
                'options'  => json_encode([
                    ['Joseph Pollack', ''],
                    ['Happ Controls', ''],
                    ['Honeywell', ''],
                    ['Otto', ''],
                    ['Colehersee', ''],
                    ['Schurter', ''],
                    ['CH Products', ''],
                    ['CTI Electronics', ''],
                    ['Molex', ''],
                    ['Penny & Giles', ''],
                    ['Sakae', ''],
                    ['Telemechanique', ''],
                    ['Advanced Input System', ''],
                    ['Bergquist', ''],
                    ['Miller Dial', ''],
                    ['None', ''],
                    ['Xymox', ''],
                    ['Nelson Nameplate', ''],
                    ['Alps', ''],
                    ['AMP', ''],
                    ['Arcolectric', ''],
                    ['Ark-Les', ''],
                    ['Augat/Alcoswitch', ''],
                    ['Carlingswitch', ''],
                    ['Cherry', ''],
                    ['CTS', ''],
                    ['Diptronics', ''],
                    ['E-Switch', ''],
                    ['EAO', ''],
                    ['Eaton', ''],
                    ['Grayhill', ''],
                    ['C&K', ''],
                    ['ITW Switches', ''],
                    ['Knitter Switch', ''],
                    ['Korry Electronics', ''],
                    ['Marquardt', ''],
                    ['Microswitch', ''],
                    ['NKK', ''],
                    ['None', ''],
                    ['Omron', ''],
                    ['Otax', ''],
                    ['Other (Specify)', ''],
                    ['SAIA-Burgess', ''],
                    ['SMK', ''],
                    ['Taiway', ''],
                    ['Berquist', ''],
                    ['Dow Switch', ''],
                    ['Eastprint', ''],
                    ['ECI Screenprint', ''],
                    ['GGI', ''],
                    ['Other (Specify)', ''],
                    ['Sun Coast', ''],
                    ['Techprint', ''],
                    ['Unknown', '']
                ]),
                'required' => true,
                'visible'  => true
            ],
            [
                'label'    => 'Year 1 Sales Volume',
                'name'     => 'year1SalesVol',
                'type'     => 'text',
                'group'    => 'Estimated Value',
                'value'    => null,
                'options'  => null,
                'required' => true,
                'visible'  => true
            ],
            [
                'label'    => 'Year 2 Sales Volume',
                'name'     => 'year2SalesVol',
                'type'     => 'text',
                'group'    => 'Estimated Value',
                'value'    => null,
                'options'  => null,
                'required' => true,
                'visible'  => true
            ],
            [
                'label'    => 'Year 3 Sales Volume',
                'name'     => 'year3SalesVol',
                'type'     => 'text',
                'group'    => 'Estimated Value',
                'value'    => null,
                'options'  => null,
                'required' => false,
                'visible'  => true
            ],
            [
                'label'    => 'Currency',
                'name'     => 'currency',
                'type'     => 'text',
                'group'    => 'Estimated Value',
                'value'    => null,
                'options'  => null,
                'required' => false,
                'visible'  => true
            ],
            [
                'label'    => 'Target Sales Price',
                'name'     => 'targetSalesPrice',
                'type'     => 'text',
                'group'    => 'Estimated Value',
                'value'    => null,
                'options'  => null,
                'required' => true,
                'visible'  => true
            ],
            [
                'label'    => 'Potential Annual Revenue',
                'name'     => 'potentialAnnualRev',
                'type'     => 'auto',
                'group'    => 'Estimated Value',
                'value'    => null,
                'options'  => null,
                'required' => false,
                'visible'  => true
            ],
            [
                'label'    => 'Probability of Win',
                'name'     => 'probabilityOfWin',
                'type'     => 'dropdown',
                'group'    => 'Estimated Value',
                'value'    => null,
                'options'  => json_encode([
                    ['0%', ''],
                    ['25%', ''],
                    ['50%', ''],
                    ['75%', ''],
                    ['100%', '']
                ]),
                'required' => true,
                'visible'  => true
            ],
            [
                'label'    => 'Expected Value',
                'name'     => 'expectedValue',
                'type'     => 'auto',
                'group'    => 'Estimated Value',
                'value'    => null,
                'options'  => null,
                'required' => false,
                'visible'  => true
            ],
            /*[
                'label'    => 'Quote Date',
                'name'     => 'quoteDate',
                'type'     => 'date',
                'group'    => 'Milestones',
                'value'    => null,
                'options'  => null,
                'required' => false,
                'visible'  => true
            ],
            [
                'label'    => 'Sample Date',
                'name'     => 'sampleDate',
                'type'     => 'date',
                'group'    => 'Milestones',
                'value'    => null,
                'options'  => null,
                'required' => false,
                'visible'  => true
            ],
            [
                'label'    => 'Approval Date',
                'name'     => 'approvalDate',
                'type'     => 'date',
                'group'    => 'Milestones',
                'value'    => null,
                'options'  => null,
                'required' => false,
                'visible'  => true
            ],
            [
                'label'    => 'Date Rcvd Prod Order',
                'name'     => 'dateRcvdProdOrder',
                'type'     => 'date',
                'group'    => 'Milestones',
                'value'    => null,
                'options'  => null,
                'required' => false,
                'visible'  => true
            ],*/
            [
                'label'    => 'Estimated Prod Date',
                'name'     => 'estimatedProdDate',
                'type'     => 'date',
                'group'    => 'Milestones',
                'value'    => null,
                'options'  => null,
                'required' => false,
                'visible'  => true
            ],
            [
                'label'    => 'Prod Sales Order Number',
                'name'     => 'prodSalesOrderNum',
                'type'     => 'text',
                'group'    => 'Milestones',
                'value'    => null,
                'options'  => null,
                'required' => false,
                'visible'  => true
            ],
            [
                'label'    => 'Reason for Win',
                'name'     => 'reasonForWin',
                'type'     => 'dropdown',
                'group'    => 'Milestones',
                'value'    => null,
                'options'  => json_encode([
                    ['Price', ''],
                    ['Lead Time', ''],
                    ['Response Time to RFQ', ''],
                    ['Product Quality', ''],
                    ['Product Innovation', ''],
                    ['Product Specification', '']
                ]),
                'required' => false,
                'visible'  => true
            ],
            [
                'label'    => 'Date Lost',
                'name'     => 'dateLost',
                'type'     => 'date',
                'group'    => 'Milestones',
                'value'    => null,
                'options'  => null,
                'required' => false,
                'visible'  => true
            ],
            [
                'label'    => 'Lost to Whom',
                'name'     => 'lostToWhom',
                'type'     => 'dropdown',
                'group'    => 'Milestones',
                'value'    => null,
                'options'  => json_encode([
                    ['Joseph Pollack', ''],
                    ['Happ Controls', ''],
                    ['Honeywell', ''],
                    ['Otto', ''],
                    ['Colehersee', ''],
                    ['Schurter', ''],
                    ['CH Products', ''],
                    ['CTI Electronics', ''],
                    ['Molex', ''],
                    ['Penny & Giles', ''],
                    ['Sakae', ''],
                    ['Telemechanique', ''],
                    ['Advanced Input System', ''],
                    ['Bergquist', ''],
                    ['Miller Dial', ''],
                    ['None', ''],
                    ['Xymox', ''],
                    ['Nelson Nameplate', ''],
                    ['Alps', ''],
                    ['AMP', ''],
                    ['Arcolectric', ''],
                    ['Ark-Les', ''],
                    ['Augat/Alcoswitch', ''],
                    ['Carlingswitch', ''],
                    ['Cherry', ''],
                    ['CTS', ''],
                    ['Diptronics', ''],
                    ['E-Switch', ''],
                    ['EAO', ''],
                    ['Eaton', ''],
                    ['Grayhill', ''],
                    ['C&K', ''],
                    ['ITW Switches', ''],
                    ['Knitter Switch', ''],
                    ['Korry Electronics', ''],
                    ['Marquardt', ''],
                    ['Microswitch', ''],
                    ['NKK', ''],
                    ['None', ''],
                    ['Omron', ''],
                    ['Otax', ''],
                    ['Other (Specify)', ''],
                    ['SAIA-Burgess', ''],
                    ['SMK', ''],
                    ['Taiway', ''],
                    ['Berquist', ''],
                    ['Dow Switch', ''],
                    ['Eastprint', ''],
                    ['ECI Screenprint', ''],
                    ['GGI', ''],
                    ['Other (Specify)', ''],
                    ['Sun Coast', ''],
                    ['Techprint', ''],
                    ['Unknown', '']
                ]),
                'required' => false,
                'visible'  => true
            ],
            [
                'label'    => 'Reason for Loss',
                'name'     => 'reasonForLoss',
                'type'     => 'dropdown',
                'group'    => 'Milestones',
                'value'    => null,
                'options'  => json_encode([
                    ['Excessive Lead Time', ''],
                    ['Price', ''],
                    ['Program Cancelled', ''],
                    ['Response Time to Quote', ''],
                    ['Technical Deficiencies', ''],
                    ['No Bid', ''],
                    ['Other', ''],
                    ['Not Known', '']
                ]),
                'required' => false,
                'visible'  => true
            ],

            [
                'label'    => 'Comment Field',
                'name'     => 'commentField',
                'type'     => 'textarea',
                'group'    => 'Comments',
                'value'    => null,
                'options'  => null,
                'required' => false,
                'visible'  => true
            ]
        ];

        DB::table('fields')->delete();

        foreach ($fields as $field) {
            $newField           = new \app\Models\Field();
            $newField->label    = $field['label'];
            $newField->name     = $field['name'];
            $newField->type     = $field['type'];
            $newField->group    = $field['group'];
            $newField->value    = $field['value'];
            $newField->options  = $field['options'];
            $newField->required = $field['required'];
            $newField->visible  = $field['visible'];
            $newField->save();
        }
    }

}
