<?php

/**
 * Created by Curious Minds Media.
 * User: Andrew Engstrom (andrew@curiousm.com)
 * Date: 7/8/16
 * Time: 1:00 PM
 */

use Illuminate\Database\Seeder;

class OpportunitySeeder extends Seeder
{

    public function run()
    {

        $faker = Faker\Factory::create();

        $numOpps = 400;

        DB::table('opportunities')->delete();

        $industries = [
            '',
            'Telecom',
            'Computers & Peripherals',
            'Medical',
            'Instrumentation',
            'Security',
            'Industrial',
            'Consumer',
            'Transportation (non-auto)',
            'Automotive',
            'Off-road',
            'Appliance',
            'Marine',
            'Mil/Aero'
        ];

        $apemSalesPerson = [
            'Klaus Sinner',
            'Kurt Ortner',
            'Josef Stahl',
            'Sabine Brandl',
            'Florian Schmidl',
            'Urban Widerdal',
            'Ann-Marie Pettersson',
            'Thierry Van Geyseghem',
            'Jean Saint-Romas',
            'Laurent Fleury',
            'Gregory Guenoun',
            'Veronique Lagasse',
            'Jean-Martial Dejean',
            'Peter Hill',
            'Mike Pearman',
            'Jim Haston',
            'Simon Nunn',
            'Adam Kroll',
            'Lynn Bagshoot',
            'Jeremy Cooke',
            'Stuart McRae',
            'Yves Foccaert',
            'Giacomo Marengo',
            'Tony West',
            'Stefan Steiner',
            'Roy Harris',
            'Ian Mcstay',
            'Richard Bateman',
            'Steve Wallen',
            'Steve Blackwell',
            'Neil Smith',
            'Ivan Gam',
            'Claus Enoch',
            'Olivier Sterckx',
            'Jochen Beckers',
            'Ann Ferrin',
            'Curt Van Parijs',
            'Allen Homonoff',
            'Peter Brouillette',
            'Tony Solis',
            'Bob Piotrowski',
            'Nadine Geeraerts',
            'Joost Van Wijngaarde',
            'Arnaud Le Nahenec',
            'Pierre-Hugues Makowski ',
            'Florence Geniez',
            'Sylvie Birou',
            'Morten Hojdevang',
            'Eric Plantie',
            'Norbert Meyers',
            'Patrick Vandenplas',
            'Alessandro Galvagno',
            'Winnie Xu',
            'Tian Yi',
            'Fei Qi Bo',
            'Guoping Xu',
            'Bryan Murphy',
            'Marc Mondeteguy',
            'Hugues Roquefort',
            'Angelique Mothes',
            'Sophie Prevost',
            'Michael Schulze',
            'Sascha Laub',
            'Manfred Holten',
            'Martin Döllinger',
            'Christoph Obermüller',
            'Céline Deloye',
            'Bernd Geebelen',
            'Brian Tovtin',
            'Magnus Edvall',
            'Mark Petersen',
            'Neil Murphy',
            'Bambi Tierney'
        ];

        $reasonForOpp = [
            'Delivery Issues',
            'New Program',
            'Price Reduction',
            'Quality Issues',
            'Vendor Reduction',
            'Other'
        ];

        $productType = [
            'Keylock',
            'Indicators',
            'MEC',
            'Industrial Control',
            'Joystick',
            'Membrane/Keyboards',
            'Other',
            'Push Button',
            'Push Wheel',
            'Rocker',
            'Rotary',
            'Rubber Keypad',
            'Slide',
            'Snap Switch',
            'SS Keypad',
            'Toggle',
            'DIP',
            'Knobs',
            'Tact',
            'Trackball',
            'Thumbwheel'
        ];

        $probOfWin = [
            '0%',
            '25%',
            '50%',
            '75%',
            '100%'
        ];

        $suppliers = [
            ['ELECTRONIQUE DIFFUSION', 'FR'],
            ['FARNELL IN ONE', 'FR'],
            ['RS ELECTRONICS, LTD.', 'GB'],
            ['FARNELL IN ONE', 'GB'],
            ['ELFA', 'SE'],
            ['YLEIS', 'SE'],
            ['KGK', 'SE'],
            ['BENNIKE AND WANDER', 'SE'],
            ['HENACO', 'SE'],
            ['FINNEKI', 'SE'],
            ['Abacus Deltron Austria Gmbh', 'DK'],
            ['NONE', 'US'],
            ['OTHER', 'US'],
            ['NONE', 'DK'],
            ['OTHER', 'DK'],
            ['NONE', 'SE'],
            ['OTHER', 'SE'],
            ['NONE', 'GB'],
            ['OTHER', 'GB'],
            ['NONE', 'FR'],
            ['OTHER', 'FR'],
            ['Abacus Deltron GmbH', 'DK'],
            ['Abacus ECC Srl', 'DK'],
            ['Active Components (NZ) Ltd.', 'DK'],
            ['APEM AB', 'DK'],
            ['APEM Benelux', 'DK'],
            ['APEM Components Ltd.', 'DK'],
            ['Asian Automation Associates Ltd', 'DK'],
            ['Associated Controls Pty. Ltd.', 'DK'],
            ['Brabek (Pty) Ltd', 'DK'],
            ['Compex GmbH', 'DK'],
            ['Constronica Lda', 'DK'],
            ['Deltron France', 'DK'],
            ['Egli, Fischer & Co. AG', 'DK'],
            ['ELPROMA Elektronika Sp. z o.o.', 'DK'],
            ['Enika spol.s r.o.', 'DK'],
            ['Ermec, SL', 'DK'],
            ['Flexitron Komponenter AB', 'DK'],
            ['Freber Norge A/S', 'DK'],
            ['General Elect. & Instr. Corp. Pte. Ltd.', 'DK'],
            ['Group Tower Electronics Ltd.', 'DK'],
            ['J.D. Friderichsen A/S', 'DK'],
            ['KPI Co. Ltd.', 'DK'],
            ['MFC Fulcrum', 'DK'],
            ['Natthapong Sales & Service Co., Ltd.', 'DK'],
            ['Nylund Group', 'DK'],
            ['Produtos Eletronicos Metaltex Ltda.', 'DK'],
            ['RS Components A/S', 'DK'],
            ['Seltronics GmbH', 'DK'],
            ['Sharon Industrial Agencies', 'DK'],
            ['Smart Electronics Ltd', 'DK'],
            ['Solico Inc.', 'DK'],
            ['Trancy Inc.', 'DK'],
            ['Vantronic S.A.', 'DK'],
            ['AD-TECH ELECTRONICS INC', 'US'],
            ['ARTLAND TECHNOLOGY LTD', 'US'],
            ['BEYOND COMPONENTS (CT)', 'US'],
            ['BROTHERS ELECTRONICS', 'US'],
            ['CARLTON-BATES', 'US'],
            ['DENVER BETA WINTRONIC', 'US'],
            ['DEPENDABLE COMPONENT SUPPLY', 'US'],
            ['DIVERSE ELECTRONICS', 'US'],
            ['GO ELECTRONICS', 'US'],
            ['HARDWARE SPECIALTY ATLANTA', 'US'],
            ['HAWK ELECTRONICS', 'US'],
            ['HEILIND ELECTRONICS', 'US'],
            ['HUGHES-PETERS', 'US'],
            ['IEC/WALKER COMPONENTS', 'US'],
            ['JFL ELECTRONICS PTE LTD', 'US'],
            ['KSM ELECTRONICS', 'US'],
            ['MARSH ELECTRONICS INC', 'US'],
            ['MASLINE ELECTRONICS INC.', 'US'],
            ['MASTER DISTRIBUTORS', 'US'],
            ['MCMASTER-CARR', 'US'],
            ['MIDAN ELECTRONICS', 'US'],
            ['MOUSER ELECTRONICS', 'US'],
            ['NEDCO (AZ)', 'US'],
            ['NEP ELECTRONICS', 'US'],
            ['NEWARK INONE', 'US'],
            ['NRC ELECTRONICS', 'US'],
            ['PROGRESSIVE IMAGE', 'US'],
            ['PROJECTIONS UNLIMITED (PUI)', 'US'],
            ['RADAR ELECTRIC CO.', 'US'],
            ['RELAY SPECIALTIES', 'US'],
            ['RUSH ELECTRONICS', 'US'],
            ['S KAHANE AGENCIES LTD', 'US'],
            ['SIMCONA', 'US'],
            ['SPEMCO', 'US'],
            ['SWITCHING DEVICES', 'US'],
            ['VOYAGER ELECTRONICS', 'US'],
            ['WES-GARDE COMPONENTS', 'US'],
            ['SELECTRONIC', 'FR'],
            ['ATLANTIQUE Composants', 'FR'],
            ['Groupe REXEL', 'FR'],
            ['PN ELECTRONICS', 'FR'],
            ['QUALISUD (Groupe Corel)', 'FR'],
            ['AVNET TIME', 'FR'],
            ['BRN Composants', 'FR'],
            ['CEL', 'FR'],
            ['ETN', 'FR'],
            ['FGET International', 'FR'],
            ['MATELCO', 'FR'],
            ['RADIALEX Wurth', 'FR'],
            ['RUTRONIK', 'FR'],
            ['ERMEC', 'FR'],
            ['REDISLOGAR', 'FR'],
            ['PEERLESS ELECTRONICS', 'US'],
            ['DigiKey', 'US'],
            ['J-Squared', 'US']
        ];

        $country = [
            'Afghanistan',
            'Albania',
            'Algeria',
            'Andorra',
            'Angola',
            'Anguilla',
            'Antarctica',
            'Antigua',
            'Argentina',
            'Armenia',
            'Aruba',
            'Australia',
            'Austria',
            'Azerbaijan',
            'Bahamas',
            'Bahrain',
            'Bangladesh',
            'Barbados',
            'Belarus',
            'Belgium',
            'Belize',
            'Benin',
            'Bermuda',
            'Bhutan',
            'Bolivia',
            'Bosnia/Hercegovina',
            'Botswana',
            'Brazil',
            'Brunei',
            'Bulgaria',
            'Burkina Faso',
            'Burma',
            'Burundi',
            'Cambodia Dem.',
            'Cameroon',
            'Canada',
            'Cape Verde',
            'Cayman Is.',
            'Central African Republic',
            'Chad',
            'Chile',
            'China',
            'Cocos Is.',
            'Colombia',
            'Comoros',
            'Congo',
            'Cook Is.',
            'Costa Rica',
            'Cote D Ivoire',
            'Croatia',
            'Cuba',
            'Cyprus',
            'Czech Republic',
            'Denmark',
            'Djibouti',
            'Dominica',
            'Dominican Rep.',
            'Ecuador',
            'Egypt',
            'El Salvador',
            'Equatorial Guinea',
            'Estonia',
            'Ethiopia',
            'Falkland Is.',
            'Faroe Is.',
            'Fiji',
            'Finland',
            'France',
            'French Guiana',
            'French Polynesia',
            'Gabon',
            'Gambia',
            'Georgia',
            'Germany',
            'Ghana',
            'Gibraltar',
            'Greece',
            'Greenland',
            'Grenada',
            'Guadeloupe',
            'Guam',
            'Guatemala',
            'Guinea',
            'Guinea-Bissau',
            'Guyana',
            'Haiti',
            'Honduras',
            'Hong Kong',
            'Hungary',
            'Iceland',
            'India',
            'Indonesia',
            'Iran',
            'Iraq',
            'Ireland',
            'Israel',
            'Italy',
            'Jamaica',
            'Japan',
            'Jordan',
            'Kazakhstan',
            'Kenya',
            'Kiribati',
            'Korea',
            'Kuwait',
            'Laos Peoples Dem. Rep.',
            'Latvia',
            'Lebanon',
            'Lesotho',
            'Liberia',
            'Libyan Arab Jamahiriya',
            'Liechtenstein',
            'Lithuania',
            'Luxembourg',
            'Macau',
            'Madagascar',
            'Malawi',
            'Malaysia',
            'Maldives',
            'Mali',
            'Malta',
            'Marshall Is.',
            'Martinique',
            'Mauritania',
            'Mauritius',
            'Mayotte',
            'Mexico',
            'Micronesia',
            'Moldova',
            'Monaco',
            'Mongolia',
            'Montserrat',
            'Morocco',
            'Mozambique',
            'Myanmar',
            'Namibia',
            'Nauru',
            'Nepal',
            'Neth. Antilles Nevis',
            'Netherlands',
            'New Caledonia',
            'New Zealand',
            'Nicaragua',
            'Niger',
            'Nigeria',
            'Niue',
            'Norfolk Is.',
            'Northern Mariana',
            'Norway',
            'Oman',
            'Pakistan',
            'Palau',
            'Panama',
            'Papua New Guinea',
            'Paraguay',
            'Peru',
            'Philippines',
            'Poland',
            'Portugal',
            'Puerto Rico',
            'Qatar',
            'Reunion',
            'Romania',
            'Russia',
            'Rwanda',
            'Samoa (American)',
            'Samoa (Western)',
            'San Marino',
            'Sao Tome & Principe',
            'Saudi Arabia',
            'Senegal',
            'Seychelles',
            'Sierra Leone',
            'Singapore',
            'Slovakia',
            'Slovenia',
            'Solomon Is.',
            'Somalia',
            'South Africa',
            'Spain',
            'Sri Lanka',
            'St. Kitts & Nevis',
            'St. Lucia',
            'St. Pierre & Miquelon',
            'St. Vincent & Grenadines',
            'Sudan',
            'Suriname',
            'Swaziland',
            'Sweden',
            'Switzerland',
            'Syrian Arab Rep.',
            'Taiwan',
            'Tajikistan',
            'Tanzania',
            'Thailand',
            'Togo',
            'Tonga',
            'Trinidad & Tobago',
            'Tunisia',
            'Turkey',
            'Turkmenistan',
            'Turks & Caicos',
            'Tuvalu',
            'Uganda',
            'Ukraine',
            'United Arab Emirates',
            'United Kingdom',
            'United States',
            'Uruguay',
            'Uzbeistan',
            'Vanuatu',
            'Vatican City',
            'Venezuela',
            'Vietnam',
            'Virgin Is. (Br.)',
            'Virgin Is. (U.S.)',
            'Wallis & Futuna',
            'Yemen Rep.',
            'Yugoslavia',
            'Zaire',
            'Zambia',
            'Zimbabwe'
        ];

        $prodSeries = [
            'Navimec',
            '660',
            '1000',
            '1500',
            '3500',
            '5000',
            '6000',
            '10600',
            '11000',
            '12000',
            '55000',
            '12000X778',
            '1600/1700',
            '21000N',
            '3600NF',
            '4600/4400',
            '600H',
            '600NH',
            'S and SF',
            'SMT TL',
            'ST',
            'TL',
            'ZL',
            '300',
            '400',
            '800',
            '1200',
            '4700',
            '4800',
            '8000',
            '9100',
            '9200',
            '9400',
            '9500',
            '9600',
            '10400',
            '13000',
            '18000',
            '1200M',
            '1200MR',
            '13000X778',
            '1400N',
            'A01',
            'A01ES',
            'A02',
            'A02ES',
            'A03',
            'A1',
            'AV',
            'IA',
            'IB-IS',
            'IF',
            'IP',
            'IT',
            'PBA',
            'PHAP40',
            'SMT TP',
            'SP',
            'TP',
            'ZP',
            'ADTS',
            'ADTS3',
            'ADTSHJM',
            'AMPT',
            'APT',
            'ATM',
            'MHPS',
            'MJTP/12mm',
            'MJTP/4mm',
            'MJTP/6mm',
            'MTP',
            '2600',
            '7000',
            'AS',
            'B',
            'FM',
            'HB',
            'KG',
            'KR',
            'MR',
            'R',
            'RH',
            'S',
            'SMT TR',
            'SR',
            'ST',
            'TR',
            '25000N',
            'G',
            'M',
            'MA',
            'MHS',
            'MHSS',
            'MJS',
            'MMS',
            'MS',
            'MSL',
            'MSS',
            'MSSA',
            'MSTS',
            'NK',
            'PM',
            'SLA',
            'SLB',
            'SLC',
            'SLG',
            'SMT TG',
            'TG',
            'CR36',
            'CR36S',
            'CR65',
            'DA',
            'DHS',
            'DM',
            'DP',
            'DPL',
            'DS',
            'DSR',
            'IKN',
            'MPG',
            'NDI',
            'NHDS',
            'P36',
            'P36S',
            'P60A',
            'P60AS',
            'PT65',
            'A1',
            'A01',
            'A02',
            'A03',
            'VL',
            'B',
            'P36',
            'P36S',
            'CR36',
            'PT65',
            'CR65',
            'P60A',
            'P60AS',
            'JD',
            'A01',
            'A02',
            '1000',
            '4000',
            '5000',
            '9000',
            'SH6/6G/6S',
            'PICOD',
            'SMCD',
            'DPS8',
            'DPS9',
            'DPS10',
            'Socket',
            'MB',
            'MA',
            'MDB1',
            'Aluminum',
            'Molded ABS',
            'Molded Phenolic',
            'MEC',
            'Membrane/Keyboards',
            'Rubber Keypads',
            'SS Keypads',
            'Other',
            'Q',
            'Multimec 3A',
            'Multimec 3C',
            'Multimec 3E',
            'Multimec 3F',
            'Illumec',
            'Varimec',
            'Aquamec',
            'Unimec',
            'Non-Catalog',
            'Non-Catalog',
            'Non-Catalog',
            'Other CH',
            'Non-Catalog',
            'Non-Catalog',
            'Non-Catalog',
            'Non-Catalog',
            'Non-Catalog',
            'Non-Catalog',
            'Non-Catalog',
            'Non-Catalog',
            'Non-Catalog',
            'Non-Catalog',
            'Non-Catalog',
            'CH Resistive Series',
            'HFX Series I',
            'HFX Series II',
            'HFX Series III',
            'HFX Series IV',
            'HFX Single Axis Throttle',
            'T-Bar Fader',
            'R Series',
            'LP Series',
            'P Series',
            'DT Series',
            'CH Rocker',
            'HFX Thumbwheel',
            '3000',
            '8000',
            'IP - USB desktops',
            'Other UK',
            'IRR',
            'IZ',
            'IPP',
            'MT',
            'CT',
            'Multimec 5G',
            'Multimec 5E',
            'Foilmec'
        ];

        $competitors = [
            'Joseph Pollack',
            'Happ Controls',
            'Honeywell',
            'Otto',
            'Colehersee',
            'Schurter',
            'CH Products',
            'CTI Electronics',
            'Molex',
            'Penny & Giles',
            'Sakae',
            'Telemechanique',
            'Advanced Input System',
            'Bergquist',
            'Miller Dial',
            'None',
            'Xymox',
            'Nelson Nameplate',
            'Alps',
            'AMP',
            'Arcolectric',
            'Ark-Les',
            'Augat/Alcoswitch',
            'Carlingswitch',
            'Cherry',
            'CTS',
            'Diptronics',
            'E-Switch',
            'EAO',
            'Eaton',
            'Grayhill',
            'C&K',
            'ITW Switches',
            'Knitter Switch',
            'Korry Electronics',
            'Marquardt',
            'Microswitch',
            'NKK',
            'None',
            'Omron',
            'Otax',
            'Other (Specify)',
            'SAIA-Burgess',
            'SMK',
            'Taiway',
            'Berquist',
            'Dow Switch',
            'Eastprint',
            'ECI Screenprint',
            'GGI',
            'Other (Specify)',
            'Sun Coast',
            'Techprint',
            'Unknown'
        ];

        $userArray = \app\Models\User::all();

        for ($i = 0; $i < $numOpps; $i ++) {
            $newOpp                          = new \app\Models\Opportunity();
            $newOpp->user_id                 = $userArray[$faker->numberBetween($min = 0, $max = 3)]->id;
            $newOpp->draft                   = $faker->numberBetween($min = 0, $max = 1);
            $newOpp->state                   = 'Open';
            $newOpp->status                  = '';
            $newOpp->stage                   = 'quote';
            $newOpp->company                 = $faker->company;
            $newOpp->address                 = $faker->address;
            $newOpp->city                    = $faker->city;
            $newOpp->state_county            = null;
            $newOpp->mail_code               = $faker->postcode;
            $newOpp->country                 = $country[ array_rand($country) ];
            $newOpp->contact_name            = $faker->name;
            $newOpp->contact_title           = $faker->title;
            $newOpp->contact_phone           = $faker->phoneNumber;
            $newOpp->contact_email           = $faker->email;
            $newOpp->sales_rep_agent         = $faker->name;
            $newOpp->distributor             = $suppliers[ array_rand($suppliers) ][0];
            $newOpp->apem_sales_person       = $apemSalesPerson[ array_rand($apemSalesPerson) ];
            $newOpp->sra_sales_rep           = $faker->name;
            $newOpp->distributor_salesperson = $faker->name;
            $newOpp->industry                = $industries[ array_rand($industries) ];
            $newOpp->application             = $faker->word;
            $newOpp->reason_for_opp          = $reasonForOpp[ array_rand($reasonForOpp) ];
            $newOpp->function                = $faker->word;
            $newOpp->catalog_product         = $faker->word;
            $newOpp->catalog_part_num        = $faker->randomNumber(null);
            $newOpp->customer_part_num       = $faker->randomNumber(null);
            $newOpp->product_type            = $productType[ array_rand($productType) ];
            $newOpp->product_series          = $prodSeries[ array_rand($prodSeries) ];
            $newOpp->apem_part_num           = $faker->randomNumber(null);
            $newOpp->brief_description       = $faker->bs;
            $newOpp->extended_description    = $faker->bs;
            $newOpp->current_supplier        = $suppliers[ array_rand($suppliers) ][0];
            $newOpp->competitors             = $competitors[ array_rand($competitors) ][0];
            $newOpp->year1_sales_vol         = $faker->randomNumber(null);
            $newOpp->year2_sales_vol         = $faker->randomNumber(null);
            $newOpp->year3_sales_vol         = $faker->randomNumber(null);
            $newOpp->currency                = $faker->randomNumber(null);
            $newOpp->target_sales_price      = $faker->randomNumber(null);
            $newOpp->potential_annual_rev    = $faker->randomNumber(null);
            $newOpp->probability_of_win      = $probOfWin[ array_rand($probOfWin) ];
            $newOpp->expected_value          = $faker->randomNumber(null);
            $newOpp->quote_date              = $faker->dateTimeThisYear($max = 'now');
            $newOpp->sample_date             = $faker->dateTimeThisYear($max = 'now');
            $newOpp->approval_date           = $faker->dateTimeThisYear($max = 'now');
            $newOpp->date_rcvd_prod_order    = $faker->dateTimeThisYear($max = 'now');
            $newOpp->estimated_prod_date     = $faker->dateTimeThisYear($max = 'now');
            $newOpp->prod_sales_order_num    = $faker->randomNumber(null);
            $newOpp->reason_for_win          = $faker->bs;
            $newOpp->date_lost               = $faker->dateTimeThisYear($max = 'now');
            $newOpp->lost_to_whom            = $faker->company;
            $newOpp->reason_for_loss         = null;
            $newOpp->comment_field           = $faker->bs;
            $newOpp->created_at              = $faker->dateTimeThisYear($max = 'now');
            $newOpp->save();

            $createEvent       = new \app\Models\Event();
            $createEvent->date = $faker->dateTimeThisYear($max = 'now');
            $createEvent->type = "create";
            $createEvent->opportunity_id = $newOpp->id;
            $createEvent->save();
        }
    }

}
